pub mod animation_data;
pub mod area_poi;
pub mod area_table;
pub mod area_trigger;
pub mod attack_anim_kits;
pub mod attack_anim_types;
pub mod auction_house;
pub mod bank_bag_slot_prices;
pub mod battlemaster_list;
pub mod camera_shakes;
pub mod cfg_categories;
pub mod cfg_configs;
pub mod char_base_info;
pub mod char_hair_geosets;
pub mod char_hair_textures;
pub mod char_sections;
pub mod char_start_outfit;
pub mod char_titles;
pub mod char_variations;
pub mod character_facial_hair_styles;
pub mod chat_channels;
pub mod chat_profanity;
pub mod chr_classes;
pub mod chr_races;
pub mod cinematic_camera;
pub mod cinematic_sequences;
pub mod creature_display_info;
pub mod creature_display_info_extra;
pub mod creature_family;
pub mod creature_model_data;
pub mod creature_sound_data;
pub mod creature_spell_data;
pub mod creature_type;
pub mod death_thud_lookups;
pub mod declined_word;
pub mod declined_word_cases;
pub mod durability_costs;
pub mod durability_quality;
pub mod emotes;
pub mod emotes_text;
pub mod emotes_text_data;
pub mod emotes_text_sound;
pub mod environmental_damage;
pub mod exhaustion;
pub mod faction;
pub mod faction_group;
pub mod faction_template;
pub mod footprint_textures;
pub mod footstep_terrain_lookup;
pub mod game_object_art_kit;
pub mod game_object_display_info;
pub mod game_tables;
pub mod game_tips;
pub mod gem_properties;
pub mod gm_survey_current_survey;
pub mod gm_survey_questions;
pub mod gm_survey_surveys;
pub mod gm_ticket_category;
pub mod ground_effect_doodad;
pub mod ground_effect_texture;
pub mod gt_chance_to_melee_crit;
pub mod gt_chance_to_melee_crit_base;
pub mod gt_chance_to_spell_crit;
pub mod gt_chance_to_spell_crit_base;
pub mod gt_combat_ratings;
pub mod gt_npc_mana_cost_scaler;
pub mod gt_oct_regen_hp;
pub mod gt_oct_regen_mp;
pub mod gt_regen_hp_per_spt;
pub mod gt_regen_mp_per_spt;
pub mod helmet_geoset_vis_data;
pub mod item;
pub mod item_bag_family;
pub mod item_class;
pub mod item_cond_ext_costs;
pub mod item_display_info;
pub mod item_extended_cost;
pub mod item_group_sounds;
pub mod item_pet_food;
pub mod item_random_properties;
pub mod item_random_suffix;
pub mod item_set;
pub mod item_sub_class;
pub mod item_sub_class_mask;
pub mod item_visual_effects;
pub mod item_visuals;
pub mod language_words;
pub mod languages;
pub mod lfg_dungeons;
pub mod light;
pub mod light_float_band;
pub mod light_int_band;
pub mod light_params;
pub mod light_skybox;
pub mod liquid_type;
pub mod loading_screen_taxi_splines;
pub mod loading_screens;
pub mod lock;
pub mod lock_type;
pub mod mail_template;
pub mod map;
pub mod material;
pub mod name_gen;
pub mod names_profanity;
pub mod names_reserved;
pub mod npc_sounds;
pub mod package;
pub mod page_text_material;
pub mod paper_doll_item_frame;
pub mod particle_color;
pub mod pet_loyalty;
pub mod pet_personality;
pub mod petition_type;
pub mod quest_info;
pub mod quest_sort;
pub mod rand_prop_points;
pub mod resistances;
pub mod server_messages;
pub mod sheathe_sound_lookups;
pub mod skill_costs_data;
pub mod skill_line;
pub mod skill_line_ability;
pub mod skill_line_category;
pub mod skill_race_class_info;
pub mod skill_tiers;
pub mod sound_ambience;
pub mod sound_entries;
pub mod sound_provider_preferences;
pub mod sound_sample_preferences;
pub mod sound_water_type;
pub mod spam_messages;
pub mod spell;
pub mod spell_cast_times;
pub mod spell_category;
pub mod spell_chain_effects;
pub mod spell_dispel_type;
pub mod spell_duration;
pub mod spell_effect_camera_shakes;
pub mod spell_focus_object;
pub mod spell_icon;
pub mod spell_item_enchantment;
pub mod spell_item_enchantment_condition;
pub mod spell_mechanic;
pub mod spell_missile_motion;
pub mod spell_radius;
pub mod spell_range;
pub mod spell_shapeshift_form;
pub mod spell_visual;
pub mod spell_visual_effect_name;
pub mod spell_visual_kit;
pub mod spell_visual_precast_transitions;
pub mod stable_slot_prices;
pub mod startup_strings;
pub mod stationery;
pub mod string_lookups;
pub mod summon_properties;
pub mod talent;
pub mod talent_tab;
pub mod taxi_nodes;
pub mod taxi_path;
pub mod taxi_path_node;
pub mod terrain_type;
pub mod terrain_type_sounds;
pub mod totem_category;
pub mod transport_animation;
pub mod transport_physics;
pub mod ui_sound_lookups;
pub mod unit_blood;
pub mod unit_blood_levels;
pub mod video_hardware;
pub mod vocal_ui_sounds;
pub mod weapon_impact_sounds;
pub mod weapon_swing_sounds2;
pub mod weather;
pub mod wmo_area_table;
pub mod world_map_area;
pub mod world_map_continent;
pub mod world_map_overlay;
pub mod world_map_transforms;
pub mod world_safe_locs;
pub mod world_state_ui;
pub mod world_state_zone_sounds;
pub mod wow_error_strings;
pub mod zone_intro_music_table;
pub mod zone_music;

use crate::{DbcTable, DbcTableEnum, DbcTableWriter};
use crate::load_table_to_enum;
#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
pub enum TbcTableName {
    AnimationData,
    AreaPOI,
    AreaTable,
    AreaTrigger,
    AttackAnimKits,
    AttackAnimTypes,
    AuctionHouse,
    BankBagSlotPrices,
    BattlemasterList,
    CameraShakes,
    Cfg_Categories,
    Cfg_Configs,
    CharBaseInfo,
    CharHairGeosets,
    CharHairTextures,
    CharSections,
    CharStartOutfit,
    CharTitles,
    CharVariations,
    CharacterFacialHairStyles,
    ChatChannels,
    ChatProfanity,
    ChrClasses,
    ChrRaces,
    CinematicCamera,
    CinematicSequences,
    CreatureDisplayInfo,
    CreatureDisplayInfoExtra,
    CreatureFamily,
    CreatureModelData,
    CreatureSoundData,
    CreatureSpellData,
    CreatureType,
    DeathThudLookups,
    DeclinedWord,
    DeclinedWordCases,
    DurabilityCosts,
    DurabilityQuality,
    Emotes,
    EmotesText,
    EmotesTextData,
    EmotesTextSound,
    EnvironmentalDamage,
    Exhaustion,
    Faction,
    FactionGroup,
    FactionTemplate,
    FootprintTextures,
    FootstepTerrainLookup,
    GMSurveyCurrentSurvey,
    GMSurveyQuestions,
    GMSurveySurveys,
    GMTicketCategory,
    GameObjectArtKit,
    GameObjectDisplayInfo,
    GameTables,
    GameTips,
    GemProperties,
    GroundEffectDoodad,
    GroundEffectTexture,
    HelmetGeosetVisData,
    Item,
    ItemBagFamily,
    ItemClass,
    ItemCondExtCosts,
    ItemDisplayInfo,
    ItemExtendedCost,
    ItemGroupSounds,
    ItemPetFood,
    ItemRandomProperties,
    ItemRandomSuffix,
    ItemSet,
    ItemSubClass,
    ItemSubClassMask,
    ItemVisualEffects,
    ItemVisuals,
    LFGDungeons,
    LanguageWords,
    Languages,
    Light,
    LightFloatBand,
    LightIntBand,
    LightParams,
    LightSkybox,
    LiquidType,
    LoadingScreenTaxiSplines,
    LoadingScreens,
    Lock,
    LockType,
    MailTemplate,
    Map,
    Material,
    NPCSounds,
    NameGen,
    NamesProfanity,
    NamesReserved,
    Package,
    PageTextMaterial,
    PaperDollItemFrame,
    ParticleColor,
    PetLoyalty,
    PetPersonality,
    PetitionType,
    QuestInfo,
    QuestSort,
    RandPropPoints,
    Resistances,
    ServerMessages,
    SheatheSoundLookups,
    SkillCostsData,
    SkillLine,
    SkillLineAbility,
    SkillLineCategory,
    SkillRaceClassInfo,
    SkillTiers,
    SoundAmbience,
    SoundEntries,
    SoundProviderPreferences,
    SoundSamplePreferences,
    SoundWaterType,
    SpamMessages,
    Spell,
    SpellCastTimes,
    SpellCategory,
    SpellChainEffects,
    SpellDispelType,
    SpellDuration,
    SpellEffectCameraShakes,
    SpellFocusObject,
    SpellIcon,
    SpellItemEnchantment,
    SpellItemEnchantmentCondition,
    SpellMechanic,
    SpellMissileMotion,
    SpellRadius,
    SpellRange,
    SpellShapeshiftForm,
    SpellVisual,
    SpellVisualEffectName,
    SpellVisualKit,
    SpellVisualPrecastTransitions,
    StableSlotPrices,
    Startup_Strings,
    Stationery,
    StringLookups,
    SummonProperties,
    Talent,
    TalentTab,
    TaxiNodes,
    TaxiPath,
    TaxiPathNode,
    TerrainType,
    TerrainTypeSounds,
    TotemCategory,
    TransportAnimation,
    TransportPhysics,
    UISoundLookups,
    UnitBlood,
    UnitBloodLevels,
    VideoHardware,
    VocalUISounds,
    WMOAreaTable,
    WeaponImpactSounds,
    WeaponSwingSounds2,
    Weather,
    WorldMapArea,
    WorldMapContinent,
    WorldMapOverlay,
    WorldMapTransforms,
    WorldSafeLocs,
    WorldStateUI,
    WorldStateZoneSounds,
    WowError_Strings,
    ZoneIntroMusicTable,
    ZoneMusic,
    gtChanceToMeleeCrit,
    gtChanceToMeleeCritBase,
    gtChanceToSpellCrit,
    gtChanceToSpellCritBase,
    gtCombatRatings,
    gtNPCManaCostScaler,
    gtOCTRegenHP,
    gtOCTRegenMP,
    gtRegenHPPerSpt,
    gtRegenMPPerSpt,
}

#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type"))]
pub enum TbcTable {
    AnimationData(animation_data::AnimationData),
    AreaPOI(area_poi::AreaPOI),
    AreaTable(area_table::AreaTable),
    AreaTrigger(area_trigger::AreaTrigger),
    AttackAnimKits(attack_anim_kits::AttackAnimKits),
    AttackAnimTypes(attack_anim_types::AttackAnimTypes),
    AuctionHouse(auction_house::AuctionHouse),
    BankBagSlotPrices(bank_bag_slot_prices::BankBagSlotPrices),
    BattlemasterList(battlemaster_list::BattlemasterList),
    CameraShakes(camera_shakes::CameraShakes),
    Cfg_Categories(cfg_categories::Cfg_Categories),
    Cfg_Configs(cfg_configs::Cfg_Configs),
    CharBaseInfo(char_base_info::CharBaseInfo),
    CharHairGeosets(char_hair_geosets::CharHairGeosets),
    CharHairTextures(char_hair_textures::CharHairTextures),
    CharSections(char_sections::CharSections),
    CharStartOutfit(char_start_outfit::CharStartOutfit),
    CharTitles(char_titles::CharTitles),
    CharVariations(char_variations::CharVariations),
    CharacterFacialHairStyles(character_facial_hair_styles::CharacterFacialHairStyles),
    ChatChannels(chat_channels::ChatChannels),
    ChatProfanity(chat_profanity::ChatProfanity),
    ChrClasses(chr_classes::ChrClasses),
    ChrRaces(chr_races::ChrRaces),
    CinematicCamera(cinematic_camera::CinematicCamera),
    CinematicSequences(cinematic_sequences::CinematicSequences),
    CreatureDisplayInfo(creature_display_info::CreatureDisplayInfo),
    CreatureDisplayInfoExtra(creature_display_info_extra::CreatureDisplayInfoExtra),
    CreatureFamily(creature_family::CreatureFamily),
    CreatureModelData(creature_model_data::CreatureModelData),
    CreatureSoundData(creature_sound_data::CreatureSoundData),
    CreatureSpellData(creature_spell_data::CreatureSpellData),
    CreatureType(creature_type::CreatureType),
    DeathThudLookups(death_thud_lookups::DeathThudLookups),
    DeclinedWord(declined_word::DeclinedWord),
    DeclinedWordCases(declined_word_cases::DeclinedWordCases),
    DurabilityCosts(durability_costs::DurabilityCosts),
    DurabilityQuality(durability_quality::DurabilityQuality),
    Emotes(emotes::Emotes),
    EmotesText(emotes_text::EmotesText),
    EmotesTextData(emotes_text_data::EmotesTextData),
    EmotesTextSound(emotes_text_sound::EmotesTextSound),
    EnvironmentalDamage(environmental_damage::EnvironmentalDamage),
    Exhaustion(exhaustion::Exhaustion),
    Faction(faction::Faction),
    FactionGroup(faction_group::FactionGroup),
    FactionTemplate(faction_template::FactionTemplate),
    FootprintTextures(footprint_textures::FootprintTextures),
    FootstepTerrainLookup(footstep_terrain_lookup::FootstepTerrainLookup),
    GMSurveyCurrentSurvey(gm_survey_current_survey::GMSurveyCurrentSurvey),
    GMSurveyQuestions(gm_survey_questions::GMSurveyQuestions),
    GMSurveySurveys(gm_survey_surveys::GMSurveySurveys),
    GMTicketCategory(gm_ticket_category::GMTicketCategory),
    GameObjectArtKit(game_object_art_kit::GameObjectArtKit),
    GameObjectDisplayInfo(game_object_display_info::GameObjectDisplayInfo),
    GameTables(game_tables::GameTables),
    GameTips(game_tips::GameTips),
    GemProperties(gem_properties::GemProperties),
    GroundEffectDoodad(ground_effect_doodad::GroundEffectDoodad),
    GroundEffectTexture(ground_effect_texture::GroundEffectTexture),
    HelmetGeosetVisData(helmet_geoset_vis_data::HelmetGeosetVisData),
    Item(item::Item),
    ItemBagFamily(item_bag_family::ItemBagFamily),
    ItemClass(item_class::ItemClass),
    ItemCondExtCosts(item_cond_ext_costs::ItemCondExtCosts),
    ItemDisplayInfo(item_display_info::ItemDisplayInfo),
    ItemExtendedCost(item_extended_cost::ItemExtendedCost),
    ItemGroupSounds(item_group_sounds::ItemGroupSounds),
    ItemPetFood(item_pet_food::ItemPetFood),
    ItemRandomProperties(item_random_properties::ItemRandomProperties),
    ItemRandomSuffix(item_random_suffix::ItemRandomSuffix),
    ItemSet(item_set::ItemSet),
    ItemSubClass(item_sub_class::ItemSubClass),
    ItemSubClassMask(item_sub_class_mask::ItemSubClassMask),
    ItemVisualEffects(item_visual_effects::ItemVisualEffects),
    ItemVisuals(item_visuals::ItemVisuals),
    LFGDungeons(lfg_dungeons::LFGDungeons),
    LanguageWords(language_words::LanguageWords),
    Languages(languages::Languages),
    Light(light::Light),
    LightFloatBand(light_float_band::LightFloatBand),
    LightIntBand(light_int_band::LightIntBand),
    LightParams(light_params::LightParams),
    LightSkybox(light_skybox::LightSkybox),
    LiquidType(liquid_type::LiquidType),
    LoadingScreenTaxiSplines(loading_screen_taxi_splines::LoadingScreenTaxiSplines),
    LoadingScreens(loading_screens::LoadingScreens),
    Lock(lock::Lock),
    LockType(lock_type::LockType),
    MailTemplate(mail_template::MailTemplate),
    Map(map::Map),
    Material(material::Material),
    NPCSounds(npc_sounds::NPCSounds),
    NameGen(name_gen::NameGen),
    NamesProfanity(names_profanity::NamesProfanity),
    NamesReserved(names_reserved::NamesReserved),
    Package(package::Package),
    PageTextMaterial(page_text_material::PageTextMaterial),
    PaperDollItemFrame(paper_doll_item_frame::PaperDollItemFrame),
    ParticleColor(particle_color::ParticleColor),
    PetLoyalty(pet_loyalty::PetLoyalty),
    PetPersonality(pet_personality::PetPersonality),
    PetitionType(petition_type::PetitionType),
    QuestInfo(quest_info::QuestInfo),
    QuestSort(quest_sort::QuestSort),
    RandPropPoints(rand_prop_points::RandPropPoints),
    Resistances(resistances::Resistances),
    ServerMessages(server_messages::ServerMessages),
    SheatheSoundLookups(sheathe_sound_lookups::SheatheSoundLookups),
    SkillCostsData(skill_costs_data::SkillCostsData),
    SkillLine(skill_line::SkillLine),
    SkillLineAbility(skill_line_ability::SkillLineAbility),
    SkillLineCategory(skill_line_category::SkillLineCategory),
    SkillRaceClassInfo(skill_race_class_info::SkillRaceClassInfo),
    SkillTiers(skill_tiers::SkillTiers),
    SoundAmbience(sound_ambience::SoundAmbience),
    SoundEntries(sound_entries::SoundEntries),
    SoundProviderPreferences(sound_provider_preferences::SoundProviderPreferences),
    SoundSamplePreferences(sound_sample_preferences::SoundSamplePreferences),
    SoundWaterType(sound_water_type::SoundWaterType),
    SpamMessages(spam_messages::SpamMessages),
    Spell(spell::Spell),
    SpellCastTimes(spell_cast_times::SpellCastTimes),
    SpellCategory(spell_category::SpellCategory),
    SpellChainEffects(spell_chain_effects::SpellChainEffects),
    SpellDispelType(spell_dispel_type::SpellDispelType),
    SpellDuration(spell_duration::SpellDuration),
    SpellEffectCameraShakes(spell_effect_camera_shakes::SpellEffectCameraShakes),
    SpellFocusObject(spell_focus_object::SpellFocusObject),
    SpellIcon(spell_icon::SpellIcon),
    SpellItemEnchantment(spell_item_enchantment::SpellItemEnchantment),
    SpellItemEnchantmentCondition(spell_item_enchantment_condition::SpellItemEnchantmentCondition),
    SpellMechanic(spell_mechanic::SpellMechanic),
    SpellMissileMotion(spell_missile_motion::SpellMissileMotion),
    SpellRadius(spell_radius::SpellRadius),
    SpellRange(spell_range::SpellRange),
    SpellShapeshiftForm(spell_shapeshift_form::SpellShapeshiftForm),
    SpellVisual(spell_visual::SpellVisual),
    SpellVisualEffectName(spell_visual_effect_name::SpellVisualEffectName),
    SpellVisualKit(spell_visual_kit::SpellVisualKit),
    SpellVisualPrecastTransitions(spell_visual_precast_transitions::SpellVisualPrecastTransitions),
    StableSlotPrices(stable_slot_prices::StableSlotPrices),
    Startup_Strings(startup_strings::Startup_Strings),
    Stationery(stationery::Stationery),
    StringLookups(string_lookups::StringLookups),
    SummonProperties(summon_properties::SummonProperties),
    Talent(talent::Talent),
    TalentTab(talent_tab::TalentTab),
    TaxiNodes(taxi_nodes::TaxiNodes),
    TaxiPath(taxi_path::TaxiPath),
    TaxiPathNode(taxi_path_node::TaxiPathNode),
    TerrainType(terrain_type::TerrainType),
    TerrainTypeSounds(terrain_type_sounds::TerrainTypeSounds),
    TotemCategory(totem_category::TotemCategory),
    TransportAnimation(transport_animation::TransportAnimation),
    TransportPhysics(transport_physics::TransportPhysics),
    UISoundLookups(ui_sound_lookups::UISoundLookups),
    UnitBlood(unit_blood::UnitBlood),
    UnitBloodLevels(unit_blood_levels::UnitBloodLevels),
    VideoHardware(video_hardware::VideoHardware),
    VocalUISounds(vocal_ui_sounds::VocalUISounds),
    WMOAreaTable(wmo_area_table::WMOAreaTable),
    WeaponImpactSounds(weapon_impact_sounds::WeaponImpactSounds),
    WeaponSwingSounds2(weapon_swing_sounds2::WeaponSwingSounds2),
    Weather(weather::Weather),
    WorldMapArea(world_map_area::WorldMapArea),
    WorldMapContinent(world_map_continent::WorldMapContinent),
    WorldMapOverlay(world_map_overlay::WorldMapOverlay),
    WorldMapTransforms(world_map_transforms::WorldMapTransforms),
    WorldSafeLocs(world_safe_locs::WorldSafeLocs),
    WorldStateUI(world_state_ui::WorldStateUI),
    WorldStateZoneSounds(world_state_zone_sounds::WorldStateZoneSounds),
    WowError_Strings(wow_error_strings::WowError_Strings),
    ZoneIntroMusicTable(zone_intro_music_table::ZoneIntroMusicTable),
    ZoneMusic(zone_music::ZoneMusic),
    gtChanceToMeleeCrit(gt_chance_to_melee_crit::gtChanceToMeleeCrit),
    gtChanceToMeleeCritBase(gt_chance_to_melee_crit_base::gtChanceToMeleeCritBase),
    gtChanceToSpellCrit(gt_chance_to_spell_crit::gtChanceToSpellCrit),
    gtChanceToSpellCritBase(gt_chance_to_spell_crit_base::gtChanceToSpellCritBase),
    gtCombatRatings(gt_combat_ratings::gtCombatRatings),
    gtNPCManaCostScaler(gt_npc_mana_cost_scaler::gtNPCManaCostScaler),
    gtOCTRegenHP(gt_oct_regen_hp::gtOCTRegenHP),
    gtOCTRegenMP(gt_oct_regen_mp::gtOCTRegenMP),
    gtRegenHPPerSpt(gt_regen_hp_per_spt::gtRegenHPPerSpt),
    gtRegenMPPerSpt(gt_regen_mp_per_spt::gtRegenMPPerSpt),
}

impl DbcTableEnum<TbcTable> for TbcTableName {
    fn load(self, b: &mut impl std::io::Read) -> Result<TbcTable, crate::DbcError> {
        match self {
            Self::AnimationData => load_table_to_enum::<animation_data::AnimationData, TbcTable>(b),
            Self::AreaPOI => load_table_to_enum::<area_poi::AreaPOI, TbcTable>(b),
            Self::AreaTable => load_table_to_enum::<area_table::AreaTable, TbcTable>(b),
            Self::AreaTrigger => load_table_to_enum::<area_trigger::AreaTrigger, TbcTable>(b),
            Self::AttackAnimKits => load_table_to_enum::<attack_anim_kits::AttackAnimKits, TbcTable>(b),
            Self::AttackAnimTypes => load_table_to_enum::<attack_anim_types::AttackAnimTypes, TbcTable>(b),
            Self::AuctionHouse => load_table_to_enum::<auction_house::AuctionHouse, TbcTable>(b),
            Self::BankBagSlotPrices => load_table_to_enum::<bank_bag_slot_prices::BankBagSlotPrices, TbcTable>(b),
            Self::BattlemasterList => load_table_to_enum::<battlemaster_list::BattlemasterList, TbcTable>(b),
            Self::CameraShakes => load_table_to_enum::<camera_shakes::CameraShakes, TbcTable>(b),
            Self::Cfg_Categories => load_table_to_enum::<cfg_categories::Cfg_Categories, TbcTable>(b),
            Self::Cfg_Configs => load_table_to_enum::<cfg_configs::Cfg_Configs, TbcTable>(b),
            Self::CharBaseInfo => load_table_to_enum::<char_base_info::CharBaseInfo, TbcTable>(b),
            Self::CharHairGeosets => load_table_to_enum::<char_hair_geosets::CharHairGeosets, TbcTable>(b),
            Self::CharHairTextures => load_table_to_enum::<char_hair_textures::CharHairTextures, TbcTable>(b),
            Self::CharSections => load_table_to_enum::<char_sections::CharSections, TbcTable>(b),
            Self::CharStartOutfit => load_table_to_enum::<char_start_outfit::CharStartOutfit, TbcTable>(b),
            Self::CharTitles => load_table_to_enum::<char_titles::CharTitles, TbcTable>(b),
            Self::CharVariations => load_table_to_enum::<char_variations::CharVariations, TbcTable>(b),
            Self::CharacterFacialHairStyles => load_table_to_enum::<character_facial_hair_styles::CharacterFacialHairStyles, TbcTable>(b),
            Self::ChatChannels => load_table_to_enum::<chat_channels::ChatChannels, TbcTable>(b),
            Self::ChatProfanity => load_table_to_enum::<chat_profanity::ChatProfanity, TbcTable>(b),
            Self::ChrClasses => load_table_to_enum::<chr_classes::ChrClasses, TbcTable>(b),
            Self::ChrRaces => load_table_to_enum::<chr_races::ChrRaces, TbcTable>(b),
            Self::CinematicCamera => load_table_to_enum::<cinematic_camera::CinematicCamera, TbcTable>(b),
            Self::CinematicSequences => load_table_to_enum::<cinematic_sequences::CinematicSequences, TbcTable>(b),
            Self::CreatureDisplayInfo => load_table_to_enum::<creature_display_info::CreatureDisplayInfo, TbcTable>(b),
            Self::CreatureDisplayInfoExtra => load_table_to_enum::<creature_display_info_extra::CreatureDisplayInfoExtra, TbcTable>(b),
            Self::CreatureFamily => load_table_to_enum::<creature_family::CreatureFamily, TbcTable>(b),
            Self::CreatureModelData => load_table_to_enum::<creature_model_data::CreatureModelData, TbcTable>(b),
            Self::CreatureSoundData => load_table_to_enum::<creature_sound_data::CreatureSoundData, TbcTable>(b),
            Self::CreatureSpellData => load_table_to_enum::<creature_spell_data::CreatureSpellData, TbcTable>(b),
            Self::CreatureType => load_table_to_enum::<creature_type::CreatureType, TbcTable>(b),
            Self::DeathThudLookups => load_table_to_enum::<death_thud_lookups::DeathThudLookups, TbcTable>(b),
            Self::DeclinedWord => load_table_to_enum::<declined_word::DeclinedWord, TbcTable>(b),
            Self::DeclinedWordCases => load_table_to_enum::<declined_word_cases::DeclinedWordCases, TbcTable>(b),
            Self::DurabilityCosts => load_table_to_enum::<durability_costs::DurabilityCosts, TbcTable>(b),
            Self::DurabilityQuality => load_table_to_enum::<durability_quality::DurabilityQuality, TbcTable>(b),
            Self::Emotes => load_table_to_enum::<emotes::Emotes, TbcTable>(b),
            Self::EmotesText => load_table_to_enum::<emotes_text::EmotesText, TbcTable>(b),
            Self::EmotesTextData => load_table_to_enum::<emotes_text_data::EmotesTextData, TbcTable>(b),
            Self::EmotesTextSound => load_table_to_enum::<emotes_text_sound::EmotesTextSound, TbcTable>(b),
            Self::EnvironmentalDamage => load_table_to_enum::<environmental_damage::EnvironmentalDamage, TbcTable>(b),
            Self::Exhaustion => load_table_to_enum::<exhaustion::Exhaustion, TbcTable>(b),
            Self::Faction => load_table_to_enum::<faction::Faction, TbcTable>(b),
            Self::FactionGroup => load_table_to_enum::<faction_group::FactionGroup, TbcTable>(b),
            Self::FactionTemplate => load_table_to_enum::<faction_template::FactionTemplate, TbcTable>(b),
            Self::FootprintTextures => load_table_to_enum::<footprint_textures::FootprintTextures, TbcTable>(b),
            Self::FootstepTerrainLookup => load_table_to_enum::<footstep_terrain_lookup::FootstepTerrainLookup, TbcTable>(b),
            Self::GMSurveyCurrentSurvey => load_table_to_enum::<gm_survey_current_survey::GMSurveyCurrentSurvey, TbcTable>(b),
            Self::GMSurveyQuestions => load_table_to_enum::<gm_survey_questions::GMSurveyQuestions, TbcTable>(b),
            Self::GMSurveySurveys => load_table_to_enum::<gm_survey_surveys::GMSurveySurveys, TbcTable>(b),
            Self::GMTicketCategory => load_table_to_enum::<gm_ticket_category::GMTicketCategory, TbcTable>(b),
            Self::GameObjectArtKit => load_table_to_enum::<game_object_art_kit::GameObjectArtKit, TbcTable>(b),
            Self::GameObjectDisplayInfo => load_table_to_enum::<game_object_display_info::GameObjectDisplayInfo, TbcTable>(b),
            Self::GameTables => load_table_to_enum::<game_tables::GameTables, TbcTable>(b),
            Self::GameTips => load_table_to_enum::<game_tips::GameTips, TbcTable>(b),
            Self::GemProperties => load_table_to_enum::<gem_properties::GemProperties, TbcTable>(b),
            Self::GroundEffectDoodad => load_table_to_enum::<ground_effect_doodad::GroundEffectDoodad, TbcTable>(b),
            Self::GroundEffectTexture => load_table_to_enum::<ground_effect_texture::GroundEffectTexture, TbcTable>(b),
            Self::HelmetGeosetVisData => load_table_to_enum::<helmet_geoset_vis_data::HelmetGeosetVisData, TbcTable>(b),
            Self::Item => load_table_to_enum::<item::Item, TbcTable>(b),
            Self::ItemBagFamily => load_table_to_enum::<item_bag_family::ItemBagFamily, TbcTable>(b),
            Self::ItemClass => load_table_to_enum::<item_class::ItemClass, TbcTable>(b),
            Self::ItemCondExtCosts => load_table_to_enum::<item_cond_ext_costs::ItemCondExtCosts, TbcTable>(b),
            Self::ItemDisplayInfo => load_table_to_enum::<item_display_info::ItemDisplayInfo, TbcTable>(b),
            Self::ItemExtendedCost => load_table_to_enum::<item_extended_cost::ItemExtendedCost, TbcTable>(b),
            Self::ItemGroupSounds => load_table_to_enum::<item_group_sounds::ItemGroupSounds, TbcTable>(b),
            Self::ItemPetFood => load_table_to_enum::<item_pet_food::ItemPetFood, TbcTable>(b),
            Self::ItemRandomProperties => load_table_to_enum::<item_random_properties::ItemRandomProperties, TbcTable>(b),
            Self::ItemRandomSuffix => load_table_to_enum::<item_random_suffix::ItemRandomSuffix, TbcTable>(b),
            Self::ItemSet => load_table_to_enum::<item_set::ItemSet, TbcTable>(b),
            Self::ItemSubClass => load_table_to_enum::<item_sub_class::ItemSubClass, TbcTable>(b),
            Self::ItemSubClassMask => load_table_to_enum::<item_sub_class_mask::ItemSubClassMask, TbcTable>(b),
            Self::ItemVisualEffects => load_table_to_enum::<item_visual_effects::ItemVisualEffects, TbcTable>(b),
            Self::ItemVisuals => load_table_to_enum::<item_visuals::ItemVisuals, TbcTable>(b),
            Self::LFGDungeons => load_table_to_enum::<lfg_dungeons::LFGDungeons, TbcTable>(b),
            Self::LanguageWords => load_table_to_enum::<language_words::LanguageWords, TbcTable>(b),
            Self::Languages => load_table_to_enum::<languages::Languages, TbcTable>(b),
            Self::Light => load_table_to_enum::<light::Light, TbcTable>(b),
            Self::LightFloatBand => load_table_to_enum::<light_float_band::LightFloatBand, TbcTable>(b),
            Self::LightIntBand => load_table_to_enum::<light_int_band::LightIntBand, TbcTable>(b),
            Self::LightParams => load_table_to_enum::<light_params::LightParams, TbcTable>(b),
            Self::LightSkybox => load_table_to_enum::<light_skybox::LightSkybox, TbcTable>(b),
            Self::LiquidType => load_table_to_enum::<liquid_type::LiquidType, TbcTable>(b),
            Self::LoadingScreenTaxiSplines => load_table_to_enum::<loading_screen_taxi_splines::LoadingScreenTaxiSplines, TbcTable>(b),
            Self::LoadingScreens => load_table_to_enum::<loading_screens::LoadingScreens, TbcTable>(b),
            Self::Lock => load_table_to_enum::<lock::Lock, TbcTable>(b),
            Self::LockType => load_table_to_enum::<lock_type::LockType, TbcTable>(b),
            Self::MailTemplate => load_table_to_enum::<mail_template::MailTemplate, TbcTable>(b),
            Self::Map => load_table_to_enum::<map::Map, TbcTable>(b),
            Self::Material => load_table_to_enum::<material::Material, TbcTable>(b),
            Self::NPCSounds => load_table_to_enum::<npc_sounds::NPCSounds, TbcTable>(b),
            Self::NameGen => load_table_to_enum::<name_gen::NameGen, TbcTable>(b),
            Self::NamesProfanity => load_table_to_enum::<names_profanity::NamesProfanity, TbcTable>(b),
            Self::NamesReserved => load_table_to_enum::<names_reserved::NamesReserved, TbcTable>(b),
            Self::Package => load_table_to_enum::<package::Package, TbcTable>(b),
            Self::PageTextMaterial => load_table_to_enum::<page_text_material::PageTextMaterial, TbcTable>(b),
            Self::PaperDollItemFrame => load_table_to_enum::<paper_doll_item_frame::PaperDollItemFrame, TbcTable>(b),
            Self::ParticleColor => load_table_to_enum::<particle_color::ParticleColor, TbcTable>(b),
            Self::PetLoyalty => load_table_to_enum::<pet_loyalty::PetLoyalty, TbcTable>(b),
            Self::PetPersonality => load_table_to_enum::<pet_personality::PetPersonality, TbcTable>(b),
            Self::PetitionType => load_table_to_enum::<petition_type::PetitionType, TbcTable>(b),
            Self::QuestInfo => load_table_to_enum::<quest_info::QuestInfo, TbcTable>(b),
            Self::QuestSort => load_table_to_enum::<quest_sort::QuestSort, TbcTable>(b),
            Self::RandPropPoints => load_table_to_enum::<rand_prop_points::RandPropPoints, TbcTable>(b),
            Self::Resistances => load_table_to_enum::<resistances::Resistances, TbcTable>(b),
            Self::ServerMessages => load_table_to_enum::<server_messages::ServerMessages, TbcTable>(b),
            Self::SheatheSoundLookups => load_table_to_enum::<sheathe_sound_lookups::SheatheSoundLookups, TbcTable>(b),
            Self::SkillCostsData => load_table_to_enum::<skill_costs_data::SkillCostsData, TbcTable>(b),
            Self::SkillLine => load_table_to_enum::<skill_line::SkillLine, TbcTable>(b),
            Self::SkillLineAbility => load_table_to_enum::<skill_line_ability::SkillLineAbility, TbcTable>(b),
            Self::SkillLineCategory => load_table_to_enum::<skill_line_category::SkillLineCategory, TbcTable>(b),
            Self::SkillRaceClassInfo => load_table_to_enum::<skill_race_class_info::SkillRaceClassInfo, TbcTable>(b),
            Self::SkillTiers => load_table_to_enum::<skill_tiers::SkillTiers, TbcTable>(b),
            Self::SoundAmbience => load_table_to_enum::<sound_ambience::SoundAmbience, TbcTable>(b),
            Self::SoundEntries => load_table_to_enum::<sound_entries::SoundEntries, TbcTable>(b),
            Self::SoundProviderPreferences => load_table_to_enum::<sound_provider_preferences::SoundProviderPreferences, TbcTable>(b),
            Self::SoundSamplePreferences => load_table_to_enum::<sound_sample_preferences::SoundSamplePreferences, TbcTable>(b),
            Self::SoundWaterType => load_table_to_enum::<sound_water_type::SoundWaterType, TbcTable>(b),
            Self::SpamMessages => load_table_to_enum::<spam_messages::SpamMessages, TbcTable>(b),
            Self::Spell => load_table_to_enum::<spell::Spell, TbcTable>(b),
            Self::SpellCastTimes => load_table_to_enum::<spell_cast_times::SpellCastTimes, TbcTable>(b),
            Self::SpellCategory => load_table_to_enum::<spell_category::SpellCategory, TbcTable>(b),
            Self::SpellChainEffects => load_table_to_enum::<spell_chain_effects::SpellChainEffects, TbcTable>(b),
            Self::SpellDispelType => load_table_to_enum::<spell_dispel_type::SpellDispelType, TbcTable>(b),
            Self::SpellDuration => load_table_to_enum::<spell_duration::SpellDuration, TbcTable>(b),
            Self::SpellEffectCameraShakes => load_table_to_enum::<spell_effect_camera_shakes::SpellEffectCameraShakes, TbcTable>(b),
            Self::SpellFocusObject => load_table_to_enum::<spell_focus_object::SpellFocusObject, TbcTable>(b),
            Self::SpellIcon => load_table_to_enum::<spell_icon::SpellIcon, TbcTable>(b),
            Self::SpellItemEnchantment => load_table_to_enum::<spell_item_enchantment::SpellItemEnchantment, TbcTable>(b),
            Self::SpellItemEnchantmentCondition => load_table_to_enum::<spell_item_enchantment_condition::SpellItemEnchantmentCondition, TbcTable>(b),
            Self::SpellMechanic => load_table_to_enum::<spell_mechanic::SpellMechanic, TbcTable>(b),
            Self::SpellMissileMotion => load_table_to_enum::<spell_missile_motion::SpellMissileMotion, TbcTable>(b),
            Self::SpellRadius => load_table_to_enum::<spell_radius::SpellRadius, TbcTable>(b),
            Self::SpellRange => load_table_to_enum::<spell_range::SpellRange, TbcTable>(b),
            Self::SpellShapeshiftForm => load_table_to_enum::<spell_shapeshift_form::SpellShapeshiftForm, TbcTable>(b),
            Self::SpellVisual => load_table_to_enum::<spell_visual::SpellVisual, TbcTable>(b),
            Self::SpellVisualEffectName => load_table_to_enum::<spell_visual_effect_name::SpellVisualEffectName, TbcTable>(b),
            Self::SpellVisualKit => load_table_to_enum::<spell_visual_kit::SpellVisualKit, TbcTable>(b),
            Self::SpellVisualPrecastTransitions => load_table_to_enum::<spell_visual_precast_transitions::SpellVisualPrecastTransitions, TbcTable>(b),
            Self::StableSlotPrices => load_table_to_enum::<stable_slot_prices::StableSlotPrices, TbcTable>(b),
            Self::Startup_Strings => load_table_to_enum::<startup_strings::Startup_Strings, TbcTable>(b),
            Self::Stationery => load_table_to_enum::<stationery::Stationery, TbcTable>(b),
            Self::StringLookups => load_table_to_enum::<string_lookups::StringLookups, TbcTable>(b),
            Self::SummonProperties => load_table_to_enum::<summon_properties::SummonProperties, TbcTable>(b),
            Self::Talent => load_table_to_enum::<talent::Talent, TbcTable>(b),
            Self::TalentTab => load_table_to_enum::<talent_tab::TalentTab, TbcTable>(b),
            Self::TaxiNodes => load_table_to_enum::<taxi_nodes::TaxiNodes, TbcTable>(b),
            Self::TaxiPath => load_table_to_enum::<taxi_path::TaxiPath, TbcTable>(b),
            Self::TaxiPathNode => load_table_to_enum::<taxi_path_node::TaxiPathNode, TbcTable>(b),
            Self::TerrainType => load_table_to_enum::<terrain_type::TerrainType, TbcTable>(b),
            Self::TerrainTypeSounds => load_table_to_enum::<terrain_type_sounds::TerrainTypeSounds, TbcTable>(b),
            Self::TotemCategory => load_table_to_enum::<totem_category::TotemCategory, TbcTable>(b),
            Self::TransportAnimation => load_table_to_enum::<transport_animation::TransportAnimation, TbcTable>(b),
            Self::TransportPhysics => load_table_to_enum::<transport_physics::TransportPhysics, TbcTable>(b),
            Self::UISoundLookups => load_table_to_enum::<ui_sound_lookups::UISoundLookups, TbcTable>(b),
            Self::UnitBlood => load_table_to_enum::<unit_blood::UnitBlood, TbcTable>(b),
            Self::UnitBloodLevels => load_table_to_enum::<unit_blood_levels::UnitBloodLevels, TbcTable>(b),
            Self::VideoHardware => load_table_to_enum::<video_hardware::VideoHardware, TbcTable>(b),
            Self::VocalUISounds => load_table_to_enum::<vocal_ui_sounds::VocalUISounds, TbcTable>(b),
            Self::WMOAreaTable => load_table_to_enum::<wmo_area_table::WMOAreaTable, TbcTable>(b),
            Self::WeaponImpactSounds => load_table_to_enum::<weapon_impact_sounds::WeaponImpactSounds, TbcTable>(b),
            Self::WeaponSwingSounds2 => load_table_to_enum::<weapon_swing_sounds2::WeaponSwingSounds2, TbcTable>(b),
            Self::Weather => load_table_to_enum::<weather::Weather, TbcTable>(b),
            Self::WorldMapArea => load_table_to_enum::<world_map_area::WorldMapArea, TbcTable>(b),
            Self::WorldMapContinent => load_table_to_enum::<world_map_continent::WorldMapContinent, TbcTable>(b),
            Self::WorldMapOverlay => load_table_to_enum::<world_map_overlay::WorldMapOverlay, TbcTable>(b),
            Self::WorldMapTransforms => load_table_to_enum::<world_map_transforms::WorldMapTransforms, TbcTable>(b),
            Self::WorldSafeLocs => load_table_to_enum::<world_safe_locs::WorldSafeLocs, TbcTable>(b),
            Self::WorldStateUI => load_table_to_enum::<world_state_ui::WorldStateUI, TbcTable>(b),
            Self::WorldStateZoneSounds => load_table_to_enum::<world_state_zone_sounds::WorldStateZoneSounds, TbcTable>(b),
            Self::WowError_Strings => load_table_to_enum::<wow_error_strings::WowError_Strings, TbcTable>(b),
            Self::ZoneIntroMusicTable => load_table_to_enum::<zone_intro_music_table::ZoneIntroMusicTable, TbcTable>(b),
            Self::ZoneMusic => load_table_to_enum::<zone_music::ZoneMusic, TbcTable>(b),
            Self::gtChanceToMeleeCrit => load_table_to_enum::<gt_chance_to_melee_crit::gtChanceToMeleeCrit, TbcTable>(b),
            Self::gtChanceToMeleeCritBase => load_table_to_enum::<gt_chance_to_melee_crit_base::gtChanceToMeleeCritBase, TbcTable>(b),
            Self::gtChanceToSpellCrit => load_table_to_enum::<gt_chance_to_spell_crit::gtChanceToSpellCrit, TbcTable>(b),
            Self::gtChanceToSpellCritBase => load_table_to_enum::<gt_chance_to_spell_crit_base::gtChanceToSpellCritBase, TbcTable>(b),
            Self::gtCombatRatings => load_table_to_enum::<gt_combat_ratings::gtCombatRatings, TbcTable>(b),
            Self::gtNPCManaCostScaler => load_table_to_enum::<gt_npc_mana_cost_scaler::gtNPCManaCostScaler, TbcTable>(b),
            Self::gtOCTRegenHP => load_table_to_enum::<gt_oct_regen_hp::gtOCTRegenHP, TbcTable>(b),
            Self::gtOCTRegenMP => load_table_to_enum::<gt_oct_regen_mp::gtOCTRegenMP, TbcTable>(b),
            Self::gtRegenHPPerSpt => load_table_to_enum::<gt_regen_hp_per_spt::gtRegenHPPerSpt, TbcTable>(b),
            Self::gtRegenMPPerSpt => load_table_to_enum::<gt_regen_mp_per_spt::gtRegenMPPerSpt, TbcTable>(b),
        }
    }

}
impl DbcTableWriter for TbcTable {
    fn write(self, w: &mut impl std::io::Write) -> Result<(), std::io::Error> {
        match self {
            Self::AnimationData(t) => t.write(w),
            Self::AreaPOI(t) => t.write(w),
            Self::AreaTable(t) => t.write(w),
            Self::AreaTrigger(t) => t.write(w),
            Self::AttackAnimKits(t) => t.write(w),
            Self::AttackAnimTypes(t) => t.write(w),
            Self::AuctionHouse(t) => t.write(w),
            Self::BankBagSlotPrices(t) => t.write(w),
            Self::BattlemasterList(t) => t.write(w),
            Self::CameraShakes(t) => t.write(w),
            Self::Cfg_Categories(t) => t.write(w),
            Self::Cfg_Configs(t) => t.write(w),
            Self::CharBaseInfo(t) => t.write(w),
            Self::CharHairGeosets(t) => t.write(w),
            Self::CharHairTextures(t) => t.write(w),
            Self::CharSections(t) => t.write(w),
            Self::CharStartOutfit(t) => t.write(w),
            Self::CharTitles(t) => t.write(w),
            Self::CharVariations(t) => t.write(w),
            Self::CharacterFacialHairStyles(t) => t.write(w),
            Self::ChatChannels(t) => t.write(w),
            Self::ChatProfanity(t) => t.write(w),
            Self::ChrClasses(t) => t.write(w),
            Self::ChrRaces(t) => t.write(w),
            Self::CinematicCamera(t) => t.write(w),
            Self::CinematicSequences(t) => t.write(w),
            Self::CreatureDisplayInfo(t) => t.write(w),
            Self::CreatureDisplayInfoExtra(t) => t.write(w),
            Self::CreatureFamily(t) => t.write(w),
            Self::CreatureModelData(t) => t.write(w),
            Self::CreatureSoundData(t) => t.write(w),
            Self::CreatureSpellData(t) => t.write(w),
            Self::CreatureType(t) => t.write(w),
            Self::DeathThudLookups(t) => t.write(w),
            Self::DeclinedWord(t) => t.write(w),
            Self::DeclinedWordCases(t) => t.write(w),
            Self::DurabilityCosts(t) => t.write(w),
            Self::DurabilityQuality(t) => t.write(w),
            Self::Emotes(t) => t.write(w),
            Self::EmotesText(t) => t.write(w),
            Self::EmotesTextData(t) => t.write(w),
            Self::EmotesTextSound(t) => t.write(w),
            Self::EnvironmentalDamage(t) => t.write(w),
            Self::Exhaustion(t) => t.write(w),
            Self::Faction(t) => t.write(w),
            Self::FactionGroup(t) => t.write(w),
            Self::FactionTemplate(t) => t.write(w),
            Self::FootprintTextures(t) => t.write(w),
            Self::FootstepTerrainLookup(t) => t.write(w),
            Self::GMSurveyCurrentSurvey(t) => t.write(w),
            Self::GMSurveyQuestions(t) => t.write(w),
            Self::GMSurveySurveys(t) => t.write(w),
            Self::GMTicketCategory(t) => t.write(w),
            Self::GameObjectArtKit(t) => t.write(w),
            Self::GameObjectDisplayInfo(t) => t.write(w),
            Self::GameTables(t) => t.write(w),
            Self::GameTips(t) => t.write(w),
            Self::GemProperties(t) => t.write(w),
            Self::GroundEffectDoodad(t) => t.write(w),
            Self::GroundEffectTexture(t) => t.write(w),
            Self::HelmetGeosetVisData(t) => t.write(w),
            Self::Item(t) => t.write(w),
            Self::ItemBagFamily(t) => t.write(w),
            Self::ItemClass(t) => t.write(w),
            Self::ItemCondExtCosts(t) => t.write(w),
            Self::ItemDisplayInfo(t) => t.write(w),
            Self::ItemExtendedCost(t) => t.write(w),
            Self::ItemGroupSounds(t) => t.write(w),
            Self::ItemPetFood(t) => t.write(w),
            Self::ItemRandomProperties(t) => t.write(w),
            Self::ItemRandomSuffix(t) => t.write(w),
            Self::ItemSet(t) => t.write(w),
            Self::ItemSubClass(t) => t.write(w),
            Self::ItemSubClassMask(t) => t.write(w),
            Self::ItemVisualEffects(t) => t.write(w),
            Self::ItemVisuals(t) => t.write(w),
            Self::LFGDungeons(t) => t.write(w),
            Self::LanguageWords(t) => t.write(w),
            Self::Languages(t) => t.write(w),
            Self::Light(t) => t.write(w),
            Self::LightFloatBand(t) => t.write(w),
            Self::LightIntBand(t) => t.write(w),
            Self::LightParams(t) => t.write(w),
            Self::LightSkybox(t) => t.write(w),
            Self::LiquidType(t) => t.write(w),
            Self::LoadingScreenTaxiSplines(t) => t.write(w),
            Self::LoadingScreens(t) => t.write(w),
            Self::Lock(t) => t.write(w),
            Self::LockType(t) => t.write(w),
            Self::MailTemplate(t) => t.write(w),
            Self::Map(t) => t.write(w),
            Self::Material(t) => t.write(w),
            Self::NPCSounds(t) => t.write(w),
            Self::NameGen(t) => t.write(w),
            Self::NamesProfanity(t) => t.write(w),
            Self::NamesReserved(t) => t.write(w),
            Self::Package(t) => t.write(w),
            Self::PageTextMaterial(t) => t.write(w),
            Self::PaperDollItemFrame(t) => t.write(w),
            Self::ParticleColor(t) => t.write(w),
            Self::PetLoyalty(t) => t.write(w),
            Self::PetPersonality(t) => t.write(w),
            Self::PetitionType(t) => t.write(w),
            Self::QuestInfo(t) => t.write(w),
            Self::QuestSort(t) => t.write(w),
            Self::RandPropPoints(t) => t.write(w),
            Self::Resistances(t) => t.write(w),
            Self::ServerMessages(t) => t.write(w),
            Self::SheatheSoundLookups(t) => t.write(w),
            Self::SkillCostsData(t) => t.write(w),
            Self::SkillLine(t) => t.write(w),
            Self::SkillLineAbility(t) => t.write(w),
            Self::SkillLineCategory(t) => t.write(w),
            Self::SkillRaceClassInfo(t) => t.write(w),
            Self::SkillTiers(t) => t.write(w),
            Self::SoundAmbience(t) => t.write(w),
            Self::SoundEntries(t) => t.write(w),
            Self::SoundProviderPreferences(t) => t.write(w),
            Self::SoundSamplePreferences(t) => t.write(w),
            Self::SoundWaterType(t) => t.write(w),
            Self::SpamMessages(t) => t.write(w),
            Self::Spell(t) => t.write(w),
            Self::SpellCastTimes(t) => t.write(w),
            Self::SpellCategory(t) => t.write(w),
            Self::SpellChainEffects(t) => t.write(w),
            Self::SpellDispelType(t) => t.write(w),
            Self::SpellDuration(t) => t.write(w),
            Self::SpellEffectCameraShakes(t) => t.write(w),
            Self::SpellFocusObject(t) => t.write(w),
            Self::SpellIcon(t) => t.write(w),
            Self::SpellItemEnchantment(t) => t.write(w),
            Self::SpellItemEnchantmentCondition(t) => t.write(w),
            Self::SpellMechanic(t) => t.write(w),
            Self::SpellMissileMotion(t) => t.write(w),
            Self::SpellRadius(t) => t.write(w),
            Self::SpellRange(t) => t.write(w),
            Self::SpellShapeshiftForm(t) => t.write(w),
            Self::SpellVisual(t) => t.write(w),
            Self::SpellVisualEffectName(t) => t.write(w),
            Self::SpellVisualKit(t) => t.write(w),
            Self::SpellVisualPrecastTransitions(t) => t.write(w),
            Self::StableSlotPrices(t) => t.write(w),
            Self::Startup_Strings(t) => t.write(w),
            Self::Stationery(t) => t.write(w),
            Self::StringLookups(t) => t.write(w),
            Self::SummonProperties(t) => t.write(w),
            Self::Talent(t) => t.write(w),
            Self::TalentTab(t) => t.write(w),
            Self::TaxiNodes(t) => t.write(w),
            Self::TaxiPath(t) => t.write(w),
            Self::TaxiPathNode(t) => t.write(w),
            Self::TerrainType(t) => t.write(w),
            Self::TerrainTypeSounds(t) => t.write(w),
            Self::TotemCategory(t) => t.write(w),
            Self::TransportAnimation(t) => t.write(w),
            Self::TransportPhysics(t) => t.write(w),
            Self::UISoundLookups(t) => t.write(w),
            Self::UnitBlood(t) => t.write(w),
            Self::UnitBloodLevels(t) => t.write(w),
            Self::VideoHardware(t) => t.write(w),
            Self::VocalUISounds(t) => t.write(w),
            Self::WMOAreaTable(t) => t.write(w),
            Self::WeaponImpactSounds(t) => t.write(w),
            Self::WeaponSwingSounds2(t) => t.write(w),
            Self::Weather(t) => t.write(w),
            Self::WorldMapArea(t) => t.write(w),
            Self::WorldMapContinent(t) => t.write(w),
            Self::WorldMapOverlay(t) => t.write(w),
            Self::WorldMapTransforms(t) => t.write(w),
            Self::WorldSafeLocs(t) => t.write(w),
            Self::WorldStateUI(t) => t.write(w),
            Self::WorldStateZoneSounds(t) => t.write(w),
            Self::WowError_Strings(t) => t.write(w),
            Self::ZoneIntroMusicTable(t) => t.write(w),
            Self::ZoneMusic(t) => t.write(w),
            Self::gtChanceToMeleeCrit(t) => t.write(w),
            Self::gtChanceToMeleeCritBase(t) => t.write(w),
            Self::gtChanceToSpellCrit(t) => t.write(w),
            Self::gtChanceToSpellCritBase(t) => t.write(w),
            Self::gtCombatRatings(t) => t.write(w),
            Self::gtNPCManaCostScaler(t) => t.write(w),
            Self::gtOCTRegenHP(t) => t.write(w),
            Self::gtOCTRegenMP(t) => t.write(w),
            Self::gtRegenHPPerSpt(t) => t.write(w),
            Self::gtRegenMPPerSpt(t) => t.write(w),
        }
    }

}
impl std::str::FromStr for TbcTableName {
    type Err = crate::DbcError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AnimationData" => Ok(TbcTableName::AnimationData),
            "AreaPOI" => Ok(TbcTableName::AreaPOI),
            "AreaTable" => Ok(TbcTableName::AreaTable),
            "AreaTrigger" => Ok(TbcTableName::AreaTrigger),
            "AttackAnimKits" => Ok(TbcTableName::AttackAnimKits),
            "AttackAnimTypes" => Ok(TbcTableName::AttackAnimTypes),
            "AuctionHouse" => Ok(TbcTableName::AuctionHouse),
            "BankBagSlotPrices" => Ok(TbcTableName::BankBagSlotPrices),
            "BattlemasterList" => Ok(TbcTableName::BattlemasterList),
            "CameraShakes" => Ok(TbcTableName::CameraShakes),
            "Cfg_Categories" => Ok(TbcTableName::Cfg_Categories),
            "Cfg_Configs" => Ok(TbcTableName::Cfg_Configs),
            "CharBaseInfo" => Ok(TbcTableName::CharBaseInfo),
            "CharHairGeosets" => Ok(TbcTableName::CharHairGeosets),
            "CharHairTextures" => Ok(TbcTableName::CharHairTextures),
            "CharSections" => Ok(TbcTableName::CharSections),
            "CharStartOutfit" => Ok(TbcTableName::CharStartOutfit),
            "CharTitles" => Ok(TbcTableName::CharTitles),
            "CharVariations" => Ok(TbcTableName::CharVariations),
            "CharacterFacialHairStyles" => Ok(TbcTableName::CharacterFacialHairStyles),
            "ChatChannels" => Ok(TbcTableName::ChatChannels),
            "ChatProfanity" => Ok(TbcTableName::ChatProfanity),
            "ChrClasses" => Ok(TbcTableName::ChrClasses),
            "ChrRaces" => Ok(TbcTableName::ChrRaces),
            "CinematicCamera" => Ok(TbcTableName::CinematicCamera),
            "CinematicSequences" => Ok(TbcTableName::CinematicSequences),
            "CreatureDisplayInfo" => Ok(TbcTableName::CreatureDisplayInfo),
            "CreatureDisplayInfoExtra" => Ok(TbcTableName::CreatureDisplayInfoExtra),
            "CreatureFamily" => Ok(TbcTableName::CreatureFamily),
            "CreatureModelData" => Ok(TbcTableName::CreatureModelData),
            "CreatureSoundData" => Ok(TbcTableName::CreatureSoundData),
            "CreatureSpellData" => Ok(TbcTableName::CreatureSpellData),
            "CreatureType" => Ok(TbcTableName::CreatureType),
            "DeathThudLookups" => Ok(TbcTableName::DeathThudLookups),
            "DeclinedWord" => Ok(TbcTableName::DeclinedWord),
            "DeclinedWordCases" => Ok(TbcTableName::DeclinedWordCases),
            "DurabilityCosts" => Ok(TbcTableName::DurabilityCosts),
            "DurabilityQuality" => Ok(TbcTableName::DurabilityQuality),
            "Emotes" => Ok(TbcTableName::Emotes),
            "EmotesText" => Ok(TbcTableName::EmotesText),
            "EmotesTextData" => Ok(TbcTableName::EmotesTextData),
            "EmotesTextSound" => Ok(TbcTableName::EmotesTextSound),
            "EnvironmentalDamage" => Ok(TbcTableName::EnvironmentalDamage),
            "Exhaustion" => Ok(TbcTableName::Exhaustion),
            "Faction" => Ok(TbcTableName::Faction),
            "FactionGroup" => Ok(TbcTableName::FactionGroup),
            "FactionTemplate" => Ok(TbcTableName::FactionTemplate),
            "FootprintTextures" => Ok(TbcTableName::FootprintTextures),
            "FootstepTerrainLookup" => Ok(TbcTableName::FootstepTerrainLookup),
            "GMSurveyCurrentSurvey" => Ok(TbcTableName::GMSurveyCurrentSurvey),
            "GMSurveyQuestions" => Ok(TbcTableName::GMSurveyQuestions),
            "GMSurveySurveys" => Ok(TbcTableName::GMSurveySurveys),
            "GMTicketCategory" => Ok(TbcTableName::GMTicketCategory),
            "GameObjectArtKit" => Ok(TbcTableName::GameObjectArtKit),
            "GameObjectDisplayInfo" => Ok(TbcTableName::GameObjectDisplayInfo),
            "GameTables" => Ok(TbcTableName::GameTables),
            "GameTips" => Ok(TbcTableName::GameTips),
            "GemProperties" => Ok(TbcTableName::GemProperties),
            "GroundEffectDoodad" => Ok(TbcTableName::GroundEffectDoodad),
            "GroundEffectTexture" => Ok(TbcTableName::GroundEffectTexture),
            "HelmetGeosetVisData" => Ok(TbcTableName::HelmetGeosetVisData),
            "Item" => Ok(TbcTableName::Item),
            "ItemBagFamily" => Ok(TbcTableName::ItemBagFamily),
            "ItemClass" => Ok(TbcTableName::ItemClass),
            "ItemCondExtCosts" => Ok(TbcTableName::ItemCondExtCosts),
            "ItemDisplayInfo" => Ok(TbcTableName::ItemDisplayInfo),
            "ItemExtendedCost" => Ok(TbcTableName::ItemExtendedCost),
            "ItemGroupSounds" => Ok(TbcTableName::ItemGroupSounds),
            "ItemPetFood" => Ok(TbcTableName::ItemPetFood),
            "ItemRandomProperties" => Ok(TbcTableName::ItemRandomProperties),
            "ItemRandomSuffix" => Ok(TbcTableName::ItemRandomSuffix),
            "ItemSet" => Ok(TbcTableName::ItemSet),
            "ItemSubClass" => Ok(TbcTableName::ItemSubClass),
            "ItemSubClassMask" => Ok(TbcTableName::ItemSubClassMask),
            "ItemVisualEffects" => Ok(TbcTableName::ItemVisualEffects),
            "ItemVisuals" => Ok(TbcTableName::ItemVisuals),
            "LFGDungeons" => Ok(TbcTableName::LFGDungeons),
            "LanguageWords" => Ok(TbcTableName::LanguageWords),
            "Languages" => Ok(TbcTableName::Languages),
            "Light" => Ok(TbcTableName::Light),
            "LightFloatBand" => Ok(TbcTableName::LightFloatBand),
            "LightIntBand" => Ok(TbcTableName::LightIntBand),
            "LightParams" => Ok(TbcTableName::LightParams),
            "LightSkybox" => Ok(TbcTableName::LightSkybox),
            "LiquidType" => Ok(TbcTableName::LiquidType),
            "LoadingScreenTaxiSplines" => Ok(TbcTableName::LoadingScreenTaxiSplines),
            "LoadingScreens" => Ok(TbcTableName::LoadingScreens),
            "Lock" => Ok(TbcTableName::Lock),
            "LockType" => Ok(TbcTableName::LockType),
            "MailTemplate" => Ok(TbcTableName::MailTemplate),
            "Map" => Ok(TbcTableName::Map),
            "Material" => Ok(TbcTableName::Material),
            "NPCSounds" => Ok(TbcTableName::NPCSounds),
            "NameGen" => Ok(TbcTableName::NameGen),
            "NamesProfanity" => Ok(TbcTableName::NamesProfanity),
            "NamesReserved" => Ok(TbcTableName::NamesReserved),
            "Package" => Ok(TbcTableName::Package),
            "PageTextMaterial" => Ok(TbcTableName::PageTextMaterial),
            "PaperDollItemFrame" => Ok(TbcTableName::PaperDollItemFrame),
            "ParticleColor" => Ok(TbcTableName::ParticleColor),
            "PetLoyalty" => Ok(TbcTableName::PetLoyalty),
            "PetPersonality" => Ok(TbcTableName::PetPersonality),
            "PetitionType" => Ok(TbcTableName::PetitionType),
            "QuestInfo" => Ok(TbcTableName::QuestInfo),
            "QuestSort" => Ok(TbcTableName::QuestSort),
            "RandPropPoints" => Ok(TbcTableName::RandPropPoints),
            "Resistances" => Ok(TbcTableName::Resistances),
            "ServerMessages" => Ok(TbcTableName::ServerMessages),
            "SheatheSoundLookups" => Ok(TbcTableName::SheatheSoundLookups),
            "SkillCostsData" => Ok(TbcTableName::SkillCostsData),
            "SkillLine" => Ok(TbcTableName::SkillLine),
            "SkillLineAbility" => Ok(TbcTableName::SkillLineAbility),
            "SkillLineCategory" => Ok(TbcTableName::SkillLineCategory),
            "SkillRaceClassInfo" => Ok(TbcTableName::SkillRaceClassInfo),
            "SkillTiers" => Ok(TbcTableName::SkillTiers),
            "SoundAmbience" => Ok(TbcTableName::SoundAmbience),
            "SoundEntries" => Ok(TbcTableName::SoundEntries),
            "SoundProviderPreferences" => Ok(TbcTableName::SoundProviderPreferences),
            "SoundSamplePreferences" => Ok(TbcTableName::SoundSamplePreferences),
            "SoundWaterType" => Ok(TbcTableName::SoundWaterType),
            "SpamMessages" => Ok(TbcTableName::SpamMessages),
            "Spell" => Ok(TbcTableName::Spell),
            "SpellCastTimes" => Ok(TbcTableName::SpellCastTimes),
            "SpellCategory" => Ok(TbcTableName::SpellCategory),
            "SpellChainEffects" => Ok(TbcTableName::SpellChainEffects),
            "SpellDispelType" => Ok(TbcTableName::SpellDispelType),
            "SpellDuration" => Ok(TbcTableName::SpellDuration),
            "SpellEffectCameraShakes" => Ok(TbcTableName::SpellEffectCameraShakes),
            "SpellFocusObject" => Ok(TbcTableName::SpellFocusObject),
            "SpellIcon" => Ok(TbcTableName::SpellIcon),
            "SpellItemEnchantment" => Ok(TbcTableName::SpellItemEnchantment),
            "SpellItemEnchantmentCondition" => Ok(TbcTableName::SpellItemEnchantmentCondition),
            "SpellMechanic" => Ok(TbcTableName::SpellMechanic),
            "SpellMissileMotion" => Ok(TbcTableName::SpellMissileMotion),
            "SpellRadius" => Ok(TbcTableName::SpellRadius),
            "SpellRange" => Ok(TbcTableName::SpellRange),
            "SpellShapeshiftForm" => Ok(TbcTableName::SpellShapeshiftForm),
            "SpellVisual" => Ok(TbcTableName::SpellVisual),
            "SpellVisualEffectName" => Ok(TbcTableName::SpellVisualEffectName),
            "SpellVisualKit" => Ok(TbcTableName::SpellVisualKit),
            "SpellVisualPrecastTransitions" => Ok(TbcTableName::SpellVisualPrecastTransitions),
            "StableSlotPrices" => Ok(TbcTableName::StableSlotPrices),
            "Startup_Strings" => Ok(TbcTableName::Startup_Strings),
            "Stationery" => Ok(TbcTableName::Stationery),
            "StringLookups" => Ok(TbcTableName::StringLookups),
            "SummonProperties" => Ok(TbcTableName::SummonProperties),
            "Talent" => Ok(TbcTableName::Talent),
            "TalentTab" => Ok(TbcTableName::TalentTab),
            "TaxiNodes" => Ok(TbcTableName::TaxiNodes),
            "TaxiPath" => Ok(TbcTableName::TaxiPath),
            "TaxiPathNode" => Ok(TbcTableName::TaxiPathNode),
            "TerrainType" => Ok(TbcTableName::TerrainType),
            "TerrainTypeSounds" => Ok(TbcTableName::TerrainTypeSounds),
            "TotemCategory" => Ok(TbcTableName::TotemCategory),
            "TransportAnimation" => Ok(TbcTableName::TransportAnimation),
            "TransportPhysics" => Ok(TbcTableName::TransportPhysics),
            "UISoundLookups" => Ok(TbcTableName::UISoundLookups),
            "UnitBlood" => Ok(TbcTableName::UnitBlood),
            "UnitBloodLevels" => Ok(TbcTableName::UnitBloodLevels),
            "VideoHardware" => Ok(TbcTableName::VideoHardware),
            "VocalUISounds" => Ok(TbcTableName::VocalUISounds),
            "WMOAreaTable" => Ok(TbcTableName::WMOAreaTable),
            "WeaponImpactSounds" => Ok(TbcTableName::WeaponImpactSounds),
            "WeaponSwingSounds2" => Ok(TbcTableName::WeaponSwingSounds2),
            "Weather" => Ok(TbcTableName::Weather),
            "WorldMapArea" => Ok(TbcTableName::WorldMapArea),
            "WorldMapContinent" => Ok(TbcTableName::WorldMapContinent),
            "WorldMapOverlay" => Ok(TbcTableName::WorldMapOverlay),
            "WorldMapTransforms" => Ok(TbcTableName::WorldMapTransforms),
            "WorldSafeLocs" => Ok(TbcTableName::WorldSafeLocs),
            "WorldStateUI" => Ok(TbcTableName::WorldStateUI),
            "WorldStateZoneSounds" => Ok(TbcTableName::WorldStateZoneSounds),
            "WowError_Strings" => Ok(TbcTableName::WowError_Strings),
            "ZoneIntroMusicTable" => Ok(TbcTableName::ZoneIntroMusicTable),
            "ZoneMusic" => Ok(TbcTableName::ZoneMusic),
            "gtChanceToMeleeCrit" => Ok(TbcTableName::gtChanceToMeleeCrit),
            "gtChanceToMeleeCritBase" => Ok(TbcTableName::gtChanceToMeleeCritBase),
            "gtChanceToSpellCrit" => Ok(TbcTableName::gtChanceToSpellCrit),
            "gtChanceToSpellCritBase" => Ok(TbcTableName::gtChanceToSpellCritBase),
            "gtCombatRatings" => Ok(TbcTableName::gtCombatRatings),
            "gtNPCManaCostScaler" => Ok(TbcTableName::gtNPCManaCostScaler),
            "gtOCTRegenHP" => Ok(TbcTableName::gtOCTRegenHP),
            "gtOCTRegenMP" => Ok(TbcTableName::gtOCTRegenMP),
            "gtRegenHPPerSpt" => Ok(TbcTableName::gtRegenHPPerSpt),
            "gtRegenMPPerSpt" => Ok(TbcTableName::gtRegenMPPerSpt),
            _ => Err(crate::DbcError::InvalidTableName(s.to_string()))
        }
    }
}

