pub mod achievement;
pub mod achievement_category;
pub mod achievement_criteria;
pub mod animation_data;
pub mod area_group;
pub mod area_poi;
pub mod area_table;
pub mod area_trigger;
pub mod attack_anim_kits;
pub mod attack_anim_types;
pub mod auction_house;
pub mod bank_bag_slot_prices;
pub mod banned_add_ons;
pub mod barber_shop_style;
pub mod battlemaster_list;
pub mod camera_shakes;
pub mod cfg_categories;
pub mod cfg_configs;
pub mod char_base_info;
pub mod char_hair_geosets;
pub mod char_hair_textures;
pub mod char_sections;
pub mod char_start_outfit;
pub mod char_titles;
pub mod char_variations;
pub mod character_facial_hair_styles;
pub mod chat_channels;
pub mod chat_profanity;
pub mod chr_classes;
pub mod chr_races;
pub mod cinematic_camera;
pub mod cinematic_sequences;
pub mod creature_display_info;
pub mod creature_display_info_extra;
pub mod creature_family;
pub mod creature_model_data;
pub mod creature_movement_info;
pub mod creature_sound_data;
pub mod creature_spell_data;
pub mod creature_type;
pub mod currency_category;
pub mod currency_types;
pub mod dance_moves;
pub mod death_thud_lookups;
pub mod declined_word;
pub mod declined_word_cases;
pub mod destructible_model_data;
pub mod dungeon_encounter;
pub mod dungeon_map;
pub mod dungeon_map_chunk;
pub mod durability_costs;
pub mod durability_quality;
pub mod emotes;
pub mod emotes_text;
pub mod emotes_text_data;
pub mod emotes_text_sound;
pub mod environmental_damage;
pub mod exhaustion;
pub mod faction;
pub mod faction_group;
pub mod faction_template;
pub mod file_data;
pub mod footprint_textures;
pub mod footstep_terrain_lookup;
pub mod game_object_art_kit;
pub mod game_object_display_info;
pub mod game_tables;
pub mod game_tips;
pub mod gem_properties;
pub mod glyph_properties;
pub mod glyph_slot;
pub mod gm_survey_answers;
pub mod gm_survey_current_survey;
pub mod gm_survey_questions;
pub mod gm_survey_surveys;
pub mod gm_ticket_category;
pub mod ground_effect_doodad;
pub mod ground_effect_texture;
pub mod gt_barber_shop_cost_base;
pub mod gt_chance_to_melee_crit;
pub mod gt_chance_to_melee_crit_base;
pub mod gt_chance_to_spell_crit;
pub mod gt_chance_to_spell_crit_base;
pub mod gt_combat_ratings;
pub mod gt_npc_mana_cost_scaler;
pub mod gt_oct_class_combat_rating_scalar;
pub mod gt_oct_regen_hp;
pub mod gt_oct_regen_mp;
pub mod gt_regen_hp_per_spt;
pub mod gt_regen_mp_per_spt;
pub mod helmet_geoset_vis_data;
pub mod holiday_descriptions;
pub mod holiday_names;
pub mod holidays;
pub mod item;
pub mod item_bag_family;
pub mod item_class;
pub mod item_cond_ext_costs;
pub mod item_display_info;
pub mod item_extended_cost;
pub mod item_group_sounds;
pub mod item_limit_category;
pub mod item_pet_food;
pub mod item_purchase_group;
pub mod item_random_properties;
pub mod item_random_suffix;
pub mod item_set;
pub mod item_sub_class;
pub mod item_sub_class_mask;
pub mod item_visual_effects;
pub mod item_visuals;
pub mod language_words;
pub mod languages;
pub mod lfg_dungeon_expansion;
pub mod lfg_dungeon_group;
pub mod lfg_dungeons;
pub mod light;
pub mod light_float_band;
pub mod light_int_band;
pub mod light_params;
pub mod light_skybox;
pub mod liquid_material;
pub mod liquid_type;
pub mod loading_screen_taxi_splines;
pub mod loading_screens;
pub mod lock;
pub mod lock_type;
pub mod mail_template;
pub mod map;
pub mod map_difficulty;
pub mod material;
pub mod movie;
pub mod movie_file_data;
pub mod movie_variation;
pub mod name_gen;
pub mod names_profanity;
pub mod names_reserved;
pub mod npc_sounds;
pub mod object_effect;
pub mod object_effect_group;
pub mod object_effect_modifier;
pub mod object_effect_package;
pub mod object_effect_package_elem;
pub mod override_spell_data;
pub mod package;
pub mod page_text_material;
pub mod paper_doll_item_frame;
pub mod particle_color;
pub mod pet_personality;
pub mod petition_type;
pub mod power_display;
pub mod pvp_difficulty;
pub mod quest_faction_reward;
pub mod quest_info;
pub mod quest_sort;
pub mod quest_xp;
pub mod rand_prop_points;
pub mod resistances;
pub mod scaling_stat_distribution;
pub mod scaling_stat_values;
pub mod screen_effect;
pub mod server_messages;
pub mod sheathe_sound_lookups;
pub mod skill_costs_data;
pub mod skill_line;
pub mod skill_line_ability;
pub mod skill_line_category;
pub mod skill_race_class_info;
pub mod skill_tiers;
pub mod sound_ambience;
pub mod sound_emitters;
pub mod sound_entries;
pub mod sound_entries_advanced;
pub mod sound_filter;
pub mod sound_filter_elem;
pub mod sound_provider_preferences;
pub mod sound_sample_preferences;
pub mod sound_water_type;
pub mod spam_messages;
pub mod spell;
pub mod spell_cast_times;
pub mod spell_category;
pub mod spell_chain_effects;
pub mod spell_description_variables;
pub mod spell_difficulty;
pub mod spell_dispel_type;
pub mod spell_duration;
pub mod spell_effect_camera_shakes;
pub mod spell_focus_object;
pub mod spell_icon;
pub mod spell_item_enchantment;
pub mod spell_item_enchantment_condition;
pub mod spell_mechanic;
pub mod spell_missile;
pub mod spell_missile_motion;
pub mod spell_radius;
pub mod spell_range;
pub mod spell_rune_cost;
pub mod spell_shapeshift_form;
pub mod spell_visual;
pub mod spell_visual_effect_name;
pub mod spell_visual_kit;
pub mod spell_visual_kit_area_model;
pub mod spell_visual_kit_model_attach;
pub mod spell_visual_precast_transitions;
pub mod stable_slot_prices;
pub mod startup_strings;
pub mod stationery;
pub mod string_lookups;
pub mod summon_properties;
pub mod talent;
pub mod talent_tab;
pub mod taxi_nodes;
pub mod taxi_path;
pub mod taxi_path_node;
pub mod team_contribution_points;
pub mod terrain_type;
pub mod terrain_type_sounds;
pub mod totem_category;
pub mod transport_animation;
pub mod transport_physics;
pub mod transport_rotation;
pub mod ui_sound_lookups;
pub mod unit_blood;
pub mod unit_blood_levels;
pub mod vehicle;
pub mod vehicle_seat;
pub mod vehicle_ui_ind_seat;
pub mod vehicle_ui_indicator;
pub mod video_hardware;
pub mod vocal_ui_sounds;
pub mod weapon_impact_sounds;
pub mod weapon_swing_sounds2;
pub mod weather;
pub mod wmo_area_table;
pub mod world_chunk_sounds;
pub mod world_map_area;
pub mod world_map_continent;
pub mod world_map_overlay;
pub mod world_map_transforms;
pub mod world_safe_locs;
pub mod world_state_ui;
pub mod world_state_zone_sounds;
pub mod wow_error_strings;
pub mod zone_intro_music_table;
pub mod zone_music;

use crate::{DbcTable, DbcTableEnum, DbcTableWriter};
use crate::load_table_to_enum;
#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
pub enum WrathTableName {
    Achievement,
    Achievement_Category,
    Achievement_Criteria,
    AnimationData,
    AreaGroup,
    AreaPOI,
    AreaTable,
    AreaTrigger,
    AttackAnimKits,
    AttackAnimTypes,
    AuctionHouse,
    BankBagSlotPrices,
    BannedAddOns,
    BarberShopStyle,
    BattlemasterList,
    CameraShakes,
    Cfg_Categories,
    Cfg_Configs,
    CharBaseInfo,
    CharHairGeosets,
    CharHairTextures,
    CharSections,
    CharStartOutfit,
    CharTitles,
    CharVariations,
    CharacterFacialHairStyles,
    ChatChannels,
    ChatProfanity,
    ChrClasses,
    ChrRaces,
    CinematicCamera,
    CinematicSequences,
    CreatureDisplayInfo,
    CreatureDisplayInfoExtra,
    CreatureFamily,
    CreatureModelData,
    CreatureMovementInfo,
    CreatureSoundData,
    CreatureSpellData,
    CreatureType,
    CurrencyCategory,
    CurrencyTypes,
    DanceMoves,
    DeathThudLookups,
    DeclinedWord,
    DeclinedWordCases,
    DestructibleModelData,
    DungeonEncounter,
    DungeonMap,
    DungeonMapChunk,
    DurabilityCosts,
    DurabilityQuality,
    Emotes,
    EmotesText,
    EmotesTextData,
    EmotesTextSound,
    EnvironmentalDamage,
    Exhaustion,
    Faction,
    FactionGroup,
    FactionTemplate,
    FileData,
    FootprintTextures,
    FootstepTerrainLookup,
    GMSurveyAnswers,
    GMSurveyCurrentSurvey,
    GMSurveyQuestions,
    GMSurveySurveys,
    GMTicketCategory,
    GameObjectArtKit,
    GameObjectDisplayInfo,
    GameTables,
    GameTips,
    GemProperties,
    GlyphProperties,
    GlyphSlot,
    GroundEffectDoodad,
    GroundEffectTexture,
    HelmetGeosetVisData,
    HolidayDescriptions,
    HolidayNames,
    Holidays,
    Item,
    ItemBagFamily,
    ItemClass,
    ItemCondExtCosts,
    ItemDisplayInfo,
    ItemExtendedCost,
    ItemGroupSounds,
    ItemLimitCategory,
    ItemPetFood,
    ItemPurchaseGroup,
    ItemRandomProperties,
    ItemRandomSuffix,
    ItemSet,
    ItemSubClass,
    ItemSubClassMask,
    ItemVisualEffects,
    ItemVisuals,
    LFGDungeonExpansion,
    LFGDungeonGroup,
    LFGDungeons,
    LanguageWords,
    Languages,
    Light,
    LightFloatBand,
    LightIntBand,
    LightParams,
    LightSkybox,
    LiquidMaterial,
    LiquidType,
    LoadingScreenTaxiSplines,
    LoadingScreens,
    Lock,
    LockType,
    MailTemplate,
    Map,
    MapDifficulty,
    Material,
    Movie,
    MovieFileData,
    MovieVariation,
    NPCSounds,
    NameGen,
    NamesProfanity,
    NamesReserved,
    ObjectEffect,
    ObjectEffectGroup,
    ObjectEffectModifier,
    ObjectEffectPackage,
    ObjectEffectPackageElem,
    OverrideSpellData,
    Package,
    PageTextMaterial,
    PaperDollItemFrame,
    ParticleColor,
    PetPersonality,
    PetitionType,
    PowerDisplay,
    PvpDifficulty,
    QuestFactionReward,
    QuestInfo,
    QuestSort,
    QuestXP,
    RandPropPoints,
    Resistances,
    ScalingStatDistribution,
    ScalingStatValues,
    ScreenEffect,
    ServerMessages,
    SheatheSoundLookups,
    SkillCostsData,
    SkillLine,
    SkillLineAbility,
    SkillLineCategory,
    SkillRaceClassInfo,
    SkillTiers,
    SoundAmbience,
    SoundEmitters,
    SoundEntries,
    SoundEntriesAdvanced,
    SoundFilter,
    SoundFilterElem,
    SoundProviderPreferences,
    SoundSamplePreferences,
    SoundWaterType,
    SpamMessages,
    Spell,
    SpellCastTimes,
    SpellCategory,
    SpellChainEffects,
    SpellDescriptionVariables,
    SpellDifficulty,
    SpellDispelType,
    SpellDuration,
    SpellEffectCameraShakes,
    SpellFocusObject,
    SpellIcon,
    SpellItemEnchantment,
    SpellItemEnchantmentCondition,
    SpellMechanic,
    SpellMissile,
    SpellMissileMotion,
    SpellRadius,
    SpellRange,
    SpellRuneCost,
    SpellShapeshiftForm,
    SpellVisual,
    SpellVisualEffectName,
    SpellVisualKit,
    SpellVisualKitAreaModel,
    SpellVisualKitModelAttach,
    SpellVisualPrecastTransitions,
    StableSlotPrices,
    Startup_Strings,
    Stationery,
    StringLookups,
    SummonProperties,
    Talent,
    TalentTab,
    TaxiNodes,
    TaxiPath,
    TaxiPathNode,
    TeamContributionPoints,
    TerrainType,
    TerrainTypeSounds,
    TotemCategory,
    TransportAnimation,
    TransportPhysics,
    TransportRotation,
    UISoundLookups,
    UnitBlood,
    UnitBloodLevels,
    Vehicle,
    VehicleSeat,
    VehicleUIIndSeat,
    VehicleUIIndicator,
    VideoHardware,
    VocalUISounds,
    WMOAreaTable,
    WeaponImpactSounds,
    WeaponSwingSounds2,
    Weather,
    WorldChunkSounds,
    WorldMapArea,
    WorldMapContinent,
    WorldMapOverlay,
    WorldMapTransforms,
    WorldSafeLocs,
    WorldStateUI,
    WorldStateZoneSounds,
    WowError_Strings,
    ZoneIntroMusicTable,
    ZoneMusic,
    gtBarberShopCostBase,
    gtChanceToMeleeCrit,
    gtChanceToMeleeCritBase,
    gtChanceToSpellCrit,
    gtChanceToSpellCritBase,
    gtCombatRatings,
    gtNPCManaCostScaler,
    gtOCTClassCombatRatingScalar,
    gtOCTRegenHP,
    gtOCTRegenMP,
    gtRegenHPPerSpt,
    gtRegenMPPerSpt,
}

#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type"))]
pub enum WrathTable {
    Achievement(achievement::Achievement),
    Achievement_Category(achievement_category::Achievement_Category),
    Achievement_Criteria(achievement_criteria::Achievement_Criteria),
    AnimationData(animation_data::AnimationData),
    AreaGroup(area_group::AreaGroup),
    AreaPOI(area_poi::AreaPOI),
    AreaTable(area_table::AreaTable),
    AreaTrigger(area_trigger::AreaTrigger),
    AttackAnimKits(attack_anim_kits::AttackAnimKits),
    AttackAnimTypes(attack_anim_types::AttackAnimTypes),
    AuctionHouse(auction_house::AuctionHouse),
    BankBagSlotPrices(bank_bag_slot_prices::BankBagSlotPrices),
    BannedAddOns(banned_add_ons::BannedAddOns),
    BarberShopStyle(barber_shop_style::BarberShopStyle),
    BattlemasterList(battlemaster_list::BattlemasterList),
    CameraShakes(camera_shakes::CameraShakes),
    Cfg_Categories(cfg_categories::Cfg_Categories),
    Cfg_Configs(cfg_configs::Cfg_Configs),
    CharBaseInfo(char_base_info::CharBaseInfo),
    CharHairGeosets(char_hair_geosets::CharHairGeosets),
    CharHairTextures(char_hair_textures::CharHairTextures),
    CharSections(char_sections::CharSections),
    CharStartOutfit(char_start_outfit::CharStartOutfit),
    CharTitles(char_titles::CharTitles),
    CharVariations(char_variations::CharVariations),
    CharacterFacialHairStyles(character_facial_hair_styles::CharacterFacialHairStyles),
    ChatChannels(chat_channels::ChatChannels),
    ChatProfanity(chat_profanity::ChatProfanity),
    ChrClasses(chr_classes::ChrClasses),
    ChrRaces(chr_races::ChrRaces),
    CinematicCamera(cinematic_camera::CinematicCamera),
    CinematicSequences(cinematic_sequences::CinematicSequences),
    CreatureDisplayInfo(creature_display_info::CreatureDisplayInfo),
    CreatureDisplayInfoExtra(creature_display_info_extra::CreatureDisplayInfoExtra),
    CreatureFamily(creature_family::CreatureFamily),
    CreatureModelData(creature_model_data::CreatureModelData),
    CreatureMovementInfo(creature_movement_info::CreatureMovementInfo),
    CreatureSoundData(creature_sound_data::CreatureSoundData),
    CreatureSpellData(creature_spell_data::CreatureSpellData),
    CreatureType(creature_type::CreatureType),
    CurrencyCategory(currency_category::CurrencyCategory),
    CurrencyTypes(currency_types::CurrencyTypes),
    DanceMoves(dance_moves::DanceMoves),
    DeathThudLookups(death_thud_lookups::DeathThudLookups),
    DeclinedWord(declined_word::DeclinedWord),
    DeclinedWordCases(declined_word_cases::DeclinedWordCases),
    DestructibleModelData(destructible_model_data::DestructibleModelData),
    DungeonEncounter(dungeon_encounter::DungeonEncounter),
    DungeonMap(dungeon_map::DungeonMap),
    DungeonMapChunk(dungeon_map_chunk::DungeonMapChunk),
    DurabilityCosts(durability_costs::DurabilityCosts),
    DurabilityQuality(durability_quality::DurabilityQuality),
    Emotes(emotes::Emotes),
    EmotesText(emotes_text::EmotesText),
    EmotesTextData(emotes_text_data::EmotesTextData),
    EmotesTextSound(emotes_text_sound::EmotesTextSound),
    EnvironmentalDamage(environmental_damage::EnvironmentalDamage),
    Exhaustion(exhaustion::Exhaustion),
    Faction(faction::Faction),
    FactionGroup(faction_group::FactionGroup),
    FactionTemplate(faction_template::FactionTemplate),
    FileData(file_data::FileData),
    FootprintTextures(footprint_textures::FootprintTextures),
    FootstepTerrainLookup(footstep_terrain_lookup::FootstepTerrainLookup),
    GMSurveyAnswers(gm_survey_answers::GMSurveyAnswers),
    GMSurveyCurrentSurvey(gm_survey_current_survey::GMSurveyCurrentSurvey),
    GMSurveyQuestions(gm_survey_questions::GMSurveyQuestions),
    GMSurveySurveys(gm_survey_surveys::GMSurveySurveys),
    GMTicketCategory(gm_ticket_category::GMTicketCategory),
    GameObjectArtKit(game_object_art_kit::GameObjectArtKit),
    GameObjectDisplayInfo(game_object_display_info::GameObjectDisplayInfo),
    GameTables(game_tables::GameTables),
    GameTips(game_tips::GameTips),
    GemProperties(gem_properties::GemProperties),
    GlyphProperties(glyph_properties::GlyphProperties),
    GlyphSlot(glyph_slot::GlyphSlot),
    GroundEffectDoodad(ground_effect_doodad::GroundEffectDoodad),
    GroundEffectTexture(ground_effect_texture::GroundEffectTexture),
    HelmetGeosetVisData(helmet_geoset_vis_data::HelmetGeosetVisData),
    HolidayDescriptions(holiday_descriptions::HolidayDescriptions),
    HolidayNames(holiday_names::HolidayNames),
    Holidays(holidays::Holidays),
    Item(item::Item),
    ItemBagFamily(item_bag_family::ItemBagFamily),
    ItemClass(item_class::ItemClass),
    ItemCondExtCosts(item_cond_ext_costs::ItemCondExtCosts),
    ItemDisplayInfo(item_display_info::ItemDisplayInfo),
    ItemExtendedCost(item_extended_cost::ItemExtendedCost),
    ItemGroupSounds(item_group_sounds::ItemGroupSounds),
    ItemLimitCategory(item_limit_category::ItemLimitCategory),
    ItemPetFood(item_pet_food::ItemPetFood),
    ItemPurchaseGroup(item_purchase_group::ItemPurchaseGroup),
    ItemRandomProperties(item_random_properties::ItemRandomProperties),
    ItemRandomSuffix(item_random_suffix::ItemRandomSuffix),
    ItemSet(item_set::ItemSet),
    ItemSubClass(item_sub_class::ItemSubClass),
    ItemSubClassMask(item_sub_class_mask::ItemSubClassMask),
    ItemVisualEffects(item_visual_effects::ItemVisualEffects),
    ItemVisuals(item_visuals::ItemVisuals),
    LFGDungeonExpansion(lfg_dungeon_expansion::LFGDungeonExpansion),
    LFGDungeonGroup(lfg_dungeon_group::LFGDungeonGroup),
    LFGDungeons(lfg_dungeons::LFGDungeons),
    LanguageWords(language_words::LanguageWords),
    Languages(languages::Languages),
    Light(light::Light),
    LightFloatBand(light_float_band::LightFloatBand),
    LightIntBand(light_int_band::LightIntBand),
    LightParams(light_params::LightParams),
    LightSkybox(light_skybox::LightSkybox),
    LiquidMaterial(liquid_material::LiquidMaterial),
    LiquidType(liquid_type::LiquidType),
    LoadingScreenTaxiSplines(loading_screen_taxi_splines::LoadingScreenTaxiSplines),
    LoadingScreens(loading_screens::LoadingScreens),
    Lock(lock::Lock),
    LockType(lock_type::LockType),
    MailTemplate(mail_template::MailTemplate),
    Map(map::Map),
    MapDifficulty(map_difficulty::MapDifficulty),
    Material(material::Material),
    Movie(movie::Movie),
    MovieFileData(movie_file_data::MovieFileData),
    MovieVariation(movie_variation::MovieVariation),
    NPCSounds(npc_sounds::NPCSounds),
    NameGen(name_gen::NameGen),
    NamesProfanity(names_profanity::NamesProfanity),
    NamesReserved(names_reserved::NamesReserved),
    ObjectEffect(object_effect::ObjectEffect),
    ObjectEffectGroup(object_effect_group::ObjectEffectGroup),
    ObjectEffectModifier(object_effect_modifier::ObjectEffectModifier),
    ObjectEffectPackage(object_effect_package::ObjectEffectPackage),
    ObjectEffectPackageElem(object_effect_package_elem::ObjectEffectPackageElem),
    OverrideSpellData(override_spell_data::OverrideSpellData),
    Package(package::Package),
    PageTextMaterial(page_text_material::PageTextMaterial),
    PaperDollItemFrame(paper_doll_item_frame::PaperDollItemFrame),
    ParticleColor(particle_color::ParticleColor),
    PetPersonality(pet_personality::PetPersonality),
    PetitionType(petition_type::PetitionType),
    PowerDisplay(power_display::PowerDisplay),
    PvpDifficulty(pvp_difficulty::PvpDifficulty),
    QuestFactionReward(quest_faction_reward::QuestFactionReward),
    QuestInfo(quest_info::QuestInfo),
    QuestSort(quest_sort::QuestSort),
    QuestXP(quest_xp::QuestXP),
    RandPropPoints(rand_prop_points::RandPropPoints),
    Resistances(resistances::Resistances),
    ScalingStatDistribution(scaling_stat_distribution::ScalingStatDistribution),
    ScalingStatValues(scaling_stat_values::ScalingStatValues),
    ScreenEffect(screen_effect::ScreenEffect),
    ServerMessages(server_messages::ServerMessages),
    SheatheSoundLookups(sheathe_sound_lookups::SheatheSoundLookups),
    SkillCostsData(skill_costs_data::SkillCostsData),
    SkillLine(skill_line::SkillLine),
    SkillLineAbility(skill_line_ability::SkillLineAbility),
    SkillLineCategory(skill_line_category::SkillLineCategory),
    SkillRaceClassInfo(skill_race_class_info::SkillRaceClassInfo),
    SkillTiers(skill_tiers::SkillTiers),
    SoundAmbience(sound_ambience::SoundAmbience),
    SoundEmitters(sound_emitters::SoundEmitters),
    SoundEntries(sound_entries::SoundEntries),
    SoundEntriesAdvanced(sound_entries_advanced::SoundEntriesAdvanced),
    SoundFilter(sound_filter::SoundFilter),
    SoundFilterElem(sound_filter_elem::SoundFilterElem),
    SoundProviderPreferences(sound_provider_preferences::SoundProviderPreferences),
    SoundSamplePreferences(sound_sample_preferences::SoundSamplePreferences),
    SoundWaterType(sound_water_type::SoundWaterType),
    SpamMessages(spam_messages::SpamMessages),
    Spell(spell::Spell),
    SpellCastTimes(spell_cast_times::SpellCastTimes),
    SpellCategory(spell_category::SpellCategory),
    SpellChainEffects(spell_chain_effects::SpellChainEffects),
    SpellDescriptionVariables(spell_description_variables::SpellDescriptionVariables),
    SpellDifficulty(spell_difficulty::SpellDifficulty),
    SpellDispelType(spell_dispel_type::SpellDispelType),
    SpellDuration(spell_duration::SpellDuration),
    SpellEffectCameraShakes(spell_effect_camera_shakes::SpellEffectCameraShakes),
    SpellFocusObject(spell_focus_object::SpellFocusObject),
    SpellIcon(spell_icon::SpellIcon),
    SpellItemEnchantment(spell_item_enchantment::SpellItemEnchantment),
    SpellItemEnchantmentCondition(spell_item_enchantment_condition::SpellItemEnchantmentCondition),
    SpellMechanic(spell_mechanic::SpellMechanic),
    SpellMissile(spell_missile::SpellMissile),
    SpellMissileMotion(spell_missile_motion::SpellMissileMotion),
    SpellRadius(spell_radius::SpellRadius),
    SpellRange(spell_range::SpellRange),
    SpellRuneCost(spell_rune_cost::SpellRuneCost),
    SpellShapeshiftForm(spell_shapeshift_form::SpellShapeshiftForm),
    SpellVisual(spell_visual::SpellVisual),
    SpellVisualEffectName(spell_visual_effect_name::SpellVisualEffectName),
    SpellVisualKit(spell_visual_kit::SpellVisualKit),
    SpellVisualKitAreaModel(spell_visual_kit_area_model::SpellVisualKitAreaModel),
    SpellVisualKitModelAttach(spell_visual_kit_model_attach::SpellVisualKitModelAttach),
    SpellVisualPrecastTransitions(spell_visual_precast_transitions::SpellVisualPrecastTransitions),
    StableSlotPrices(stable_slot_prices::StableSlotPrices),
    Startup_Strings(startup_strings::Startup_Strings),
    Stationery(stationery::Stationery),
    StringLookups(string_lookups::StringLookups),
    SummonProperties(summon_properties::SummonProperties),
    Talent(talent::Talent),
    TalentTab(talent_tab::TalentTab),
    TaxiNodes(taxi_nodes::TaxiNodes),
    TaxiPath(taxi_path::TaxiPath),
    TaxiPathNode(taxi_path_node::TaxiPathNode),
    TeamContributionPoints(team_contribution_points::TeamContributionPoints),
    TerrainType(terrain_type::TerrainType),
    TerrainTypeSounds(terrain_type_sounds::TerrainTypeSounds),
    TotemCategory(totem_category::TotemCategory),
    TransportAnimation(transport_animation::TransportAnimation),
    TransportPhysics(transport_physics::TransportPhysics),
    TransportRotation(transport_rotation::TransportRotation),
    UISoundLookups(ui_sound_lookups::UISoundLookups),
    UnitBlood(unit_blood::UnitBlood),
    UnitBloodLevels(unit_blood_levels::UnitBloodLevels),
    Vehicle(vehicle::Vehicle),
    VehicleSeat(vehicle_seat::VehicleSeat),
    VehicleUIIndSeat(vehicle_ui_ind_seat::VehicleUIIndSeat),
    VehicleUIIndicator(vehicle_ui_indicator::VehicleUIIndicator),
    VideoHardware(video_hardware::VideoHardware),
    VocalUISounds(vocal_ui_sounds::VocalUISounds),
    WMOAreaTable(wmo_area_table::WMOAreaTable),
    WeaponImpactSounds(weapon_impact_sounds::WeaponImpactSounds),
    WeaponSwingSounds2(weapon_swing_sounds2::WeaponSwingSounds2),
    Weather(weather::Weather),
    WorldChunkSounds(world_chunk_sounds::WorldChunkSounds),
    WorldMapArea(world_map_area::WorldMapArea),
    WorldMapContinent(world_map_continent::WorldMapContinent),
    WorldMapOverlay(world_map_overlay::WorldMapOverlay),
    WorldMapTransforms(world_map_transforms::WorldMapTransforms),
    WorldSafeLocs(world_safe_locs::WorldSafeLocs),
    WorldStateUI(world_state_ui::WorldStateUI),
    WorldStateZoneSounds(world_state_zone_sounds::WorldStateZoneSounds),
    WowError_Strings(wow_error_strings::WowError_Strings),
    ZoneIntroMusicTable(zone_intro_music_table::ZoneIntroMusicTable),
    ZoneMusic(zone_music::ZoneMusic),
    gtBarberShopCostBase(gt_barber_shop_cost_base::gtBarberShopCostBase),
    gtChanceToMeleeCrit(gt_chance_to_melee_crit::gtChanceToMeleeCrit),
    gtChanceToMeleeCritBase(gt_chance_to_melee_crit_base::gtChanceToMeleeCritBase),
    gtChanceToSpellCrit(gt_chance_to_spell_crit::gtChanceToSpellCrit),
    gtChanceToSpellCritBase(gt_chance_to_spell_crit_base::gtChanceToSpellCritBase),
    gtCombatRatings(gt_combat_ratings::gtCombatRatings),
    gtNPCManaCostScaler(gt_npc_mana_cost_scaler::gtNPCManaCostScaler),
    gtOCTClassCombatRatingScalar(gt_oct_class_combat_rating_scalar::gtOCTClassCombatRatingScalar),
    gtOCTRegenHP(gt_oct_regen_hp::gtOCTRegenHP),
    gtOCTRegenMP(gt_oct_regen_mp::gtOCTRegenMP),
    gtRegenHPPerSpt(gt_regen_hp_per_spt::gtRegenHPPerSpt),
    gtRegenMPPerSpt(gt_regen_mp_per_spt::gtRegenMPPerSpt),
}

impl DbcTableEnum<WrathTable> for WrathTableName {
    fn load(self, b: &mut impl std::io::Read) -> Result<WrathTable, crate::DbcError> {
        match self {
            Self::Achievement => load_table_to_enum::<achievement::Achievement, WrathTable>(b),
            Self::Achievement_Category => load_table_to_enum::<achievement_category::Achievement_Category, WrathTable>(b),
            Self::Achievement_Criteria => load_table_to_enum::<achievement_criteria::Achievement_Criteria, WrathTable>(b),
            Self::AnimationData => load_table_to_enum::<animation_data::AnimationData, WrathTable>(b),
            Self::AreaGroup => load_table_to_enum::<area_group::AreaGroup, WrathTable>(b),
            Self::AreaPOI => load_table_to_enum::<area_poi::AreaPOI, WrathTable>(b),
            Self::AreaTable => load_table_to_enum::<area_table::AreaTable, WrathTable>(b),
            Self::AreaTrigger => load_table_to_enum::<area_trigger::AreaTrigger, WrathTable>(b),
            Self::AttackAnimKits => load_table_to_enum::<attack_anim_kits::AttackAnimKits, WrathTable>(b),
            Self::AttackAnimTypes => load_table_to_enum::<attack_anim_types::AttackAnimTypes, WrathTable>(b),
            Self::AuctionHouse => load_table_to_enum::<auction_house::AuctionHouse, WrathTable>(b),
            Self::BankBagSlotPrices => load_table_to_enum::<bank_bag_slot_prices::BankBagSlotPrices, WrathTable>(b),
            Self::BannedAddOns => load_table_to_enum::<banned_add_ons::BannedAddOns, WrathTable>(b),
            Self::BarberShopStyle => load_table_to_enum::<barber_shop_style::BarberShopStyle, WrathTable>(b),
            Self::BattlemasterList => load_table_to_enum::<battlemaster_list::BattlemasterList, WrathTable>(b),
            Self::CameraShakes => load_table_to_enum::<camera_shakes::CameraShakes, WrathTable>(b),
            Self::Cfg_Categories => load_table_to_enum::<cfg_categories::Cfg_Categories, WrathTable>(b),
            Self::Cfg_Configs => load_table_to_enum::<cfg_configs::Cfg_Configs, WrathTable>(b),
            Self::CharBaseInfo => load_table_to_enum::<char_base_info::CharBaseInfo, WrathTable>(b),
            Self::CharHairGeosets => load_table_to_enum::<char_hair_geosets::CharHairGeosets, WrathTable>(b),
            Self::CharHairTextures => load_table_to_enum::<char_hair_textures::CharHairTextures, WrathTable>(b),
            Self::CharSections => load_table_to_enum::<char_sections::CharSections, WrathTable>(b),
            Self::CharStartOutfit => load_table_to_enum::<char_start_outfit::CharStartOutfit, WrathTable>(b),
            Self::CharTitles => load_table_to_enum::<char_titles::CharTitles, WrathTable>(b),
            Self::CharVariations => load_table_to_enum::<char_variations::CharVariations, WrathTable>(b),
            Self::CharacterFacialHairStyles => load_table_to_enum::<character_facial_hair_styles::CharacterFacialHairStyles, WrathTable>(b),
            Self::ChatChannels => load_table_to_enum::<chat_channels::ChatChannels, WrathTable>(b),
            Self::ChatProfanity => load_table_to_enum::<chat_profanity::ChatProfanity, WrathTable>(b),
            Self::ChrClasses => load_table_to_enum::<chr_classes::ChrClasses, WrathTable>(b),
            Self::ChrRaces => load_table_to_enum::<chr_races::ChrRaces, WrathTable>(b),
            Self::CinematicCamera => load_table_to_enum::<cinematic_camera::CinematicCamera, WrathTable>(b),
            Self::CinematicSequences => load_table_to_enum::<cinematic_sequences::CinematicSequences, WrathTable>(b),
            Self::CreatureDisplayInfo => load_table_to_enum::<creature_display_info::CreatureDisplayInfo, WrathTable>(b),
            Self::CreatureDisplayInfoExtra => load_table_to_enum::<creature_display_info_extra::CreatureDisplayInfoExtra, WrathTable>(b),
            Self::CreatureFamily => load_table_to_enum::<creature_family::CreatureFamily, WrathTable>(b),
            Self::CreatureModelData => load_table_to_enum::<creature_model_data::CreatureModelData, WrathTable>(b),
            Self::CreatureMovementInfo => load_table_to_enum::<creature_movement_info::CreatureMovementInfo, WrathTable>(b),
            Self::CreatureSoundData => load_table_to_enum::<creature_sound_data::CreatureSoundData, WrathTable>(b),
            Self::CreatureSpellData => load_table_to_enum::<creature_spell_data::CreatureSpellData, WrathTable>(b),
            Self::CreatureType => load_table_to_enum::<creature_type::CreatureType, WrathTable>(b),
            Self::CurrencyCategory => load_table_to_enum::<currency_category::CurrencyCategory, WrathTable>(b),
            Self::CurrencyTypes => load_table_to_enum::<currency_types::CurrencyTypes, WrathTable>(b),
            Self::DanceMoves => load_table_to_enum::<dance_moves::DanceMoves, WrathTable>(b),
            Self::DeathThudLookups => load_table_to_enum::<death_thud_lookups::DeathThudLookups, WrathTable>(b),
            Self::DeclinedWord => load_table_to_enum::<declined_word::DeclinedWord, WrathTable>(b),
            Self::DeclinedWordCases => load_table_to_enum::<declined_word_cases::DeclinedWordCases, WrathTable>(b),
            Self::DestructibleModelData => load_table_to_enum::<destructible_model_data::DestructibleModelData, WrathTable>(b),
            Self::DungeonEncounter => load_table_to_enum::<dungeon_encounter::DungeonEncounter, WrathTable>(b),
            Self::DungeonMap => load_table_to_enum::<dungeon_map::DungeonMap, WrathTable>(b),
            Self::DungeonMapChunk => load_table_to_enum::<dungeon_map_chunk::DungeonMapChunk, WrathTable>(b),
            Self::DurabilityCosts => load_table_to_enum::<durability_costs::DurabilityCosts, WrathTable>(b),
            Self::DurabilityQuality => load_table_to_enum::<durability_quality::DurabilityQuality, WrathTable>(b),
            Self::Emotes => load_table_to_enum::<emotes::Emotes, WrathTable>(b),
            Self::EmotesText => load_table_to_enum::<emotes_text::EmotesText, WrathTable>(b),
            Self::EmotesTextData => load_table_to_enum::<emotes_text_data::EmotesTextData, WrathTable>(b),
            Self::EmotesTextSound => load_table_to_enum::<emotes_text_sound::EmotesTextSound, WrathTable>(b),
            Self::EnvironmentalDamage => load_table_to_enum::<environmental_damage::EnvironmentalDamage, WrathTable>(b),
            Self::Exhaustion => load_table_to_enum::<exhaustion::Exhaustion, WrathTable>(b),
            Self::Faction => load_table_to_enum::<faction::Faction, WrathTable>(b),
            Self::FactionGroup => load_table_to_enum::<faction_group::FactionGroup, WrathTable>(b),
            Self::FactionTemplate => load_table_to_enum::<faction_template::FactionTemplate, WrathTable>(b),
            Self::FileData => load_table_to_enum::<file_data::FileData, WrathTable>(b),
            Self::FootprintTextures => load_table_to_enum::<footprint_textures::FootprintTextures, WrathTable>(b),
            Self::FootstepTerrainLookup => load_table_to_enum::<footstep_terrain_lookup::FootstepTerrainLookup, WrathTable>(b),
            Self::GMSurveyAnswers => load_table_to_enum::<gm_survey_answers::GMSurveyAnswers, WrathTable>(b),
            Self::GMSurveyCurrentSurvey => load_table_to_enum::<gm_survey_current_survey::GMSurveyCurrentSurvey, WrathTable>(b),
            Self::GMSurveyQuestions => load_table_to_enum::<gm_survey_questions::GMSurveyQuestions, WrathTable>(b),
            Self::GMSurveySurveys => load_table_to_enum::<gm_survey_surveys::GMSurveySurveys, WrathTable>(b),
            Self::GMTicketCategory => load_table_to_enum::<gm_ticket_category::GMTicketCategory, WrathTable>(b),
            Self::GameObjectArtKit => load_table_to_enum::<game_object_art_kit::GameObjectArtKit, WrathTable>(b),
            Self::GameObjectDisplayInfo => load_table_to_enum::<game_object_display_info::GameObjectDisplayInfo, WrathTable>(b),
            Self::GameTables => load_table_to_enum::<game_tables::GameTables, WrathTable>(b),
            Self::GameTips => load_table_to_enum::<game_tips::GameTips, WrathTable>(b),
            Self::GemProperties => load_table_to_enum::<gem_properties::GemProperties, WrathTable>(b),
            Self::GlyphProperties => load_table_to_enum::<glyph_properties::GlyphProperties, WrathTable>(b),
            Self::GlyphSlot => load_table_to_enum::<glyph_slot::GlyphSlot, WrathTable>(b),
            Self::GroundEffectDoodad => load_table_to_enum::<ground_effect_doodad::GroundEffectDoodad, WrathTable>(b),
            Self::GroundEffectTexture => load_table_to_enum::<ground_effect_texture::GroundEffectTexture, WrathTable>(b),
            Self::HelmetGeosetVisData => load_table_to_enum::<helmet_geoset_vis_data::HelmetGeosetVisData, WrathTable>(b),
            Self::HolidayDescriptions => load_table_to_enum::<holiday_descriptions::HolidayDescriptions, WrathTable>(b),
            Self::HolidayNames => load_table_to_enum::<holiday_names::HolidayNames, WrathTable>(b),
            Self::Holidays => load_table_to_enum::<holidays::Holidays, WrathTable>(b),
            Self::Item => load_table_to_enum::<item::Item, WrathTable>(b),
            Self::ItemBagFamily => load_table_to_enum::<item_bag_family::ItemBagFamily, WrathTable>(b),
            Self::ItemClass => load_table_to_enum::<item_class::ItemClass, WrathTable>(b),
            Self::ItemCondExtCosts => load_table_to_enum::<item_cond_ext_costs::ItemCondExtCosts, WrathTable>(b),
            Self::ItemDisplayInfo => load_table_to_enum::<item_display_info::ItemDisplayInfo, WrathTable>(b),
            Self::ItemExtendedCost => load_table_to_enum::<item_extended_cost::ItemExtendedCost, WrathTable>(b),
            Self::ItemGroupSounds => load_table_to_enum::<item_group_sounds::ItemGroupSounds, WrathTable>(b),
            Self::ItemLimitCategory => load_table_to_enum::<item_limit_category::ItemLimitCategory, WrathTable>(b),
            Self::ItemPetFood => load_table_to_enum::<item_pet_food::ItemPetFood, WrathTable>(b),
            Self::ItemPurchaseGroup => load_table_to_enum::<item_purchase_group::ItemPurchaseGroup, WrathTable>(b),
            Self::ItemRandomProperties => load_table_to_enum::<item_random_properties::ItemRandomProperties, WrathTable>(b),
            Self::ItemRandomSuffix => load_table_to_enum::<item_random_suffix::ItemRandomSuffix, WrathTable>(b),
            Self::ItemSet => load_table_to_enum::<item_set::ItemSet, WrathTable>(b),
            Self::ItemSubClass => load_table_to_enum::<item_sub_class::ItemSubClass, WrathTable>(b),
            Self::ItemSubClassMask => load_table_to_enum::<item_sub_class_mask::ItemSubClassMask, WrathTable>(b),
            Self::ItemVisualEffects => load_table_to_enum::<item_visual_effects::ItemVisualEffects, WrathTable>(b),
            Self::ItemVisuals => load_table_to_enum::<item_visuals::ItemVisuals, WrathTable>(b),
            Self::LFGDungeonExpansion => load_table_to_enum::<lfg_dungeon_expansion::LFGDungeonExpansion, WrathTable>(b),
            Self::LFGDungeonGroup => load_table_to_enum::<lfg_dungeon_group::LFGDungeonGroup, WrathTable>(b),
            Self::LFGDungeons => load_table_to_enum::<lfg_dungeons::LFGDungeons, WrathTable>(b),
            Self::LanguageWords => load_table_to_enum::<language_words::LanguageWords, WrathTable>(b),
            Self::Languages => load_table_to_enum::<languages::Languages, WrathTable>(b),
            Self::Light => load_table_to_enum::<light::Light, WrathTable>(b),
            Self::LightFloatBand => load_table_to_enum::<light_float_band::LightFloatBand, WrathTable>(b),
            Self::LightIntBand => load_table_to_enum::<light_int_band::LightIntBand, WrathTable>(b),
            Self::LightParams => load_table_to_enum::<light_params::LightParams, WrathTable>(b),
            Self::LightSkybox => load_table_to_enum::<light_skybox::LightSkybox, WrathTable>(b),
            Self::LiquidMaterial => load_table_to_enum::<liquid_material::LiquidMaterial, WrathTable>(b),
            Self::LiquidType => load_table_to_enum::<liquid_type::LiquidType, WrathTable>(b),
            Self::LoadingScreenTaxiSplines => load_table_to_enum::<loading_screen_taxi_splines::LoadingScreenTaxiSplines, WrathTable>(b),
            Self::LoadingScreens => load_table_to_enum::<loading_screens::LoadingScreens, WrathTable>(b),
            Self::Lock => load_table_to_enum::<lock::Lock, WrathTable>(b),
            Self::LockType => load_table_to_enum::<lock_type::LockType, WrathTable>(b),
            Self::MailTemplate => load_table_to_enum::<mail_template::MailTemplate, WrathTable>(b),
            Self::Map => load_table_to_enum::<map::Map, WrathTable>(b),
            Self::MapDifficulty => load_table_to_enum::<map_difficulty::MapDifficulty, WrathTable>(b),
            Self::Material => load_table_to_enum::<material::Material, WrathTable>(b),
            Self::Movie => load_table_to_enum::<movie::Movie, WrathTable>(b),
            Self::MovieFileData => load_table_to_enum::<movie_file_data::MovieFileData, WrathTable>(b),
            Self::MovieVariation => load_table_to_enum::<movie_variation::MovieVariation, WrathTable>(b),
            Self::NPCSounds => load_table_to_enum::<npc_sounds::NPCSounds, WrathTable>(b),
            Self::NameGen => load_table_to_enum::<name_gen::NameGen, WrathTable>(b),
            Self::NamesProfanity => load_table_to_enum::<names_profanity::NamesProfanity, WrathTable>(b),
            Self::NamesReserved => load_table_to_enum::<names_reserved::NamesReserved, WrathTable>(b),
            Self::ObjectEffect => load_table_to_enum::<object_effect::ObjectEffect, WrathTable>(b),
            Self::ObjectEffectGroup => load_table_to_enum::<object_effect_group::ObjectEffectGroup, WrathTable>(b),
            Self::ObjectEffectModifier => load_table_to_enum::<object_effect_modifier::ObjectEffectModifier, WrathTable>(b),
            Self::ObjectEffectPackage => load_table_to_enum::<object_effect_package::ObjectEffectPackage, WrathTable>(b),
            Self::ObjectEffectPackageElem => load_table_to_enum::<object_effect_package_elem::ObjectEffectPackageElem, WrathTable>(b),
            Self::OverrideSpellData => load_table_to_enum::<override_spell_data::OverrideSpellData, WrathTable>(b),
            Self::Package => load_table_to_enum::<package::Package, WrathTable>(b),
            Self::PageTextMaterial => load_table_to_enum::<page_text_material::PageTextMaterial, WrathTable>(b),
            Self::PaperDollItemFrame => load_table_to_enum::<paper_doll_item_frame::PaperDollItemFrame, WrathTable>(b),
            Self::ParticleColor => load_table_to_enum::<particle_color::ParticleColor, WrathTable>(b),
            Self::PetPersonality => load_table_to_enum::<pet_personality::PetPersonality, WrathTable>(b),
            Self::PetitionType => load_table_to_enum::<petition_type::PetitionType, WrathTable>(b),
            Self::PowerDisplay => load_table_to_enum::<power_display::PowerDisplay, WrathTable>(b),
            Self::PvpDifficulty => load_table_to_enum::<pvp_difficulty::PvpDifficulty, WrathTable>(b),
            Self::QuestFactionReward => load_table_to_enum::<quest_faction_reward::QuestFactionReward, WrathTable>(b),
            Self::QuestInfo => load_table_to_enum::<quest_info::QuestInfo, WrathTable>(b),
            Self::QuestSort => load_table_to_enum::<quest_sort::QuestSort, WrathTable>(b),
            Self::QuestXP => load_table_to_enum::<quest_xp::QuestXP, WrathTable>(b),
            Self::RandPropPoints => load_table_to_enum::<rand_prop_points::RandPropPoints, WrathTable>(b),
            Self::Resistances => load_table_to_enum::<resistances::Resistances, WrathTable>(b),
            Self::ScalingStatDistribution => load_table_to_enum::<scaling_stat_distribution::ScalingStatDistribution, WrathTable>(b),
            Self::ScalingStatValues => load_table_to_enum::<scaling_stat_values::ScalingStatValues, WrathTable>(b),
            Self::ScreenEffect => load_table_to_enum::<screen_effect::ScreenEffect, WrathTable>(b),
            Self::ServerMessages => load_table_to_enum::<server_messages::ServerMessages, WrathTable>(b),
            Self::SheatheSoundLookups => load_table_to_enum::<sheathe_sound_lookups::SheatheSoundLookups, WrathTable>(b),
            Self::SkillCostsData => load_table_to_enum::<skill_costs_data::SkillCostsData, WrathTable>(b),
            Self::SkillLine => load_table_to_enum::<skill_line::SkillLine, WrathTable>(b),
            Self::SkillLineAbility => load_table_to_enum::<skill_line_ability::SkillLineAbility, WrathTable>(b),
            Self::SkillLineCategory => load_table_to_enum::<skill_line_category::SkillLineCategory, WrathTable>(b),
            Self::SkillRaceClassInfo => load_table_to_enum::<skill_race_class_info::SkillRaceClassInfo, WrathTable>(b),
            Self::SkillTiers => load_table_to_enum::<skill_tiers::SkillTiers, WrathTable>(b),
            Self::SoundAmbience => load_table_to_enum::<sound_ambience::SoundAmbience, WrathTable>(b),
            Self::SoundEmitters => load_table_to_enum::<sound_emitters::SoundEmitters, WrathTable>(b),
            Self::SoundEntries => load_table_to_enum::<sound_entries::SoundEntries, WrathTable>(b),
            Self::SoundEntriesAdvanced => load_table_to_enum::<sound_entries_advanced::SoundEntriesAdvanced, WrathTable>(b),
            Self::SoundFilter => load_table_to_enum::<sound_filter::SoundFilter, WrathTable>(b),
            Self::SoundFilterElem => load_table_to_enum::<sound_filter_elem::SoundFilterElem, WrathTable>(b),
            Self::SoundProviderPreferences => load_table_to_enum::<sound_provider_preferences::SoundProviderPreferences, WrathTable>(b),
            Self::SoundSamplePreferences => load_table_to_enum::<sound_sample_preferences::SoundSamplePreferences, WrathTable>(b),
            Self::SoundWaterType => load_table_to_enum::<sound_water_type::SoundWaterType, WrathTable>(b),
            Self::SpamMessages => load_table_to_enum::<spam_messages::SpamMessages, WrathTable>(b),
            Self::Spell => load_table_to_enum::<spell::Spell, WrathTable>(b),
            Self::SpellCastTimes => load_table_to_enum::<spell_cast_times::SpellCastTimes, WrathTable>(b),
            Self::SpellCategory => load_table_to_enum::<spell_category::SpellCategory, WrathTable>(b),
            Self::SpellChainEffects => load_table_to_enum::<spell_chain_effects::SpellChainEffects, WrathTable>(b),
            Self::SpellDescriptionVariables => load_table_to_enum::<spell_description_variables::SpellDescriptionVariables, WrathTable>(b),
            Self::SpellDifficulty => load_table_to_enum::<spell_difficulty::SpellDifficulty, WrathTable>(b),
            Self::SpellDispelType => load_table_to_enum::<spell_dispel_type::SpellDispelType, WrathTable>(b),
            Self::SpellDuration => load_table_to_enum::<spell_duration::SpellDuration, WrathTable>(b),
            Self::SpellEffectCameraShakes => load_table_to_enum::<spell_effect_camera_shakes::SpellEffectCameraShakes, WrathTable>(b),
            Self::SpellFocusObject => load_table_to_enum::<spell_focus_object::SpellFocusObject, WrathTable>(b),
            Self::SpellIcon => load_table_to_enum::<spell_icon::SpellIcon, WrathTable>(b),
            Self::SpellItemEnchantment => load_table_to_enum::<spell_item_enchantment::SpellItemEnchantment, WrathTable>(b),
            Self::SpellItemEnchantmentCondition => load_table_to_enum::<spell_item_enchantment_condition::SpellItemEnchantmentCondition, WrathTable>(b),
            Self::SpellMechanic => load_table_to_enum::<spell_mechanic::SpellMechanic, WrathTable>(b),
            Self::SpellMissile => load_table_to_enum::<spell_missile::SpellMissile, WrathTable>(b),
            Self::SpellMissileMotion => load_table_to_enum::<spell_missile_motion::SpellMissileMotion, WrathTable>(b),
            Self::SpellRadius => load_table_to_enum::<spell_radius::SpellRadius, WrathTable>(b),
            Self::SpellRange => load_table_to_enum::<spell_range::SpellRange, WrathTable>(b),
            Self::SpellRuneCost => load_table_to_enum::<spell_rune_cost::SpellRuneCost, WrathTable>(b),
            Self::SpellShapeshiftForm => load_table_to_enum::<spell_shapeshift_form::SpellShapeshiftForm, WrathTable>(b),
            Self::SpellVisual => load_table_to_enum::<spell_visual::SpellVisual, WrathTable>(b),
            Self::SpellVisualEffectName => load_table_to_enum::<spell_visual_effect_name::SpellVisualEffectName, WrathTable>(b),
            Self::SpellVisualKit => load_table_to_enum::<spell_visual_kit::SpellVisualKit, WrathTable>(b),
            Self::SpellVisualKitAreaModel => load_table_to_enum::<spell_visual_kit_area_model::SpellVisualKitAreaModel, WrathTable>(b),
            Self::SpellVisualKitModelAttach => load_table_to_enum::<spell_visual_kit_model_attach::SpellVisualKitModelAttach, WrathTable>(b),
            Self::SpellVisualPrecastTransitions => load_table_to_enum::<spell_visual_precast_transitions::SpellVisualPrecastTransitions, WrathTable>(b),
            Self::StableSlotPrices => load_table_to_enum::<stable_slot_prices::StableSlotPrices, WrathTable>(b),
            Self::Startup_Strings => load_table_to_enum::<startup_strings::Startup_Strings, WrathTable>(b),
            Self::Stationery => load_table_to_enum::<stationery::Stationery, WrathTable>(b),
            Self::StringLookups => load_table_to_enum::<string_lookups::StringLookups, WrathTable>(b),
            Self::SummonProperties => load_table_to_enum::<summon_properties::SummonProperties, WrathTable>(b),
            Self::Talent => load_table_to_enum::<talent::Talent, WrathTable>(b),
            Self::TalentTab => load_table_to_enum::<talent_tab::TalentTab, WrathTable>(b),
            Self::TaxiNodes => load_table_to_enum::<taxi_nodes::TaxiNodes, WrathTable>(b),
            Self::TaxiPath => load_table_to_enum::<taxi_path::TaxiPath, WrathTable>(b),
            Self::TaxiPathNode => load_table_to_enum::<taxi_path_node::TaxiPathNode, WrathTable>(b),
            Self::TeamContributionPoints => load_table_to_enum::<team_contribution_points::TeamContributionPoints, WrathTable>(b),
            Self::TerrainType => load_table_to_enum::<terrain_type::TerrainType, WrathTable>(b),
            Self::TerrainTypeSounds => load_table_to_enum::<terrain_type_sounds::TerrainTypeSounds, WrathTable>(b),
            Self::TotemCategory => load_table_to_enum::<totem_category::TotemCategory, WrathTable>(b),
            Self::TransportAnimation => load_table_to_enum::<transport_animation::TransportAnimation, WrathTable>(b),
            Self::TransportPhysics => load_table_to_enum::<transport_physics::TransportPhysics, WrathTable>(b),
            Self::TransportRotation => load_table_to_enum::<transport_rotation::TransportRotation, WrathTable>(b),
            Self::UISoundLookups => load_table_to_enum::<ui_sound_lookups::UISoundLookups, WrathTable>(b),
            Self::UnitBlood => load_table_to_enum::<unit_blood::UnitBlood, WrathTable>(b),
            Self::UnitBloodLevels => load_table_to_enum::<unit_blood_levels::UnitBloodLevels, WrathTable>(b),
            Self::Vehicle => load_table_to_enum::<vehicle::Vehicle, WrathTable>(b),
            Self::VehicleSeat => load_table_to_enum::<vehicle_seat::VehicleSeat, WrathTable>(b),
            Self::VehicleUIIndSeat => load_table_to_enum::<vehicle_ui_ind_seat::VehicleUIIndSeat, WrathTable>(b),
            Self::VehicleUIIndicator => load_table_to_enum::<vehicle_ui_indicator::VehicleUIIndicator, WrathTable>(b),
            Self::VideoHardware => load_table_to_enum::<video_hardware::VideoHardware, WrathTable>(b),
            Self::VocalUISounds => load_table_to_enum::<vocal_ui_sounds::VocalUISounds, WrathTable>(b),
            Self::WMOAreaTable => load_table_to_enum::<wmo_area_table::WMOAreaTable, WrathTable>(b),
            Self::WeaponImpactSounds => load_table_to_enum::<weapon_impact_sounds::WeaponImpactSounds, WrathTable>(b),
            Self::WeaponSwingSounds2 => load_table_to_enum::<weapon_swing_sounds2::WeaponSwingSounds2, WrathTable>(b),
            Self::Weather => load_table_to_enum::<weather::Weather, WrathTable>(b),
            Self::WorldChunkSounds => load_table_to_enum::<world_chunk_sounds::WorldChunkSounds, WrathTable>(b),
            Self::WorldMapArea => load_table_to_enum::<world_map_area::WorldMapArea, WrathTable>(b),
            Self::WorldMapContinent => load_table_to_enum::<world_map_continent::WorldMapContinent, WrathTable>(b),
            Self::WorldMapOverlay => load_table_to_enum::<world_map_overlay::WorldMapOverlay, WrathTable>(b),
            Self::WorldMapTransforms => load_table_to_enum::<world_map_transforms::WorldMapTransforms, WrathTable>(b),
            Self::WorldSafeLocs => load_table_to_enum::<world_safe_locs::WorldSafeLocs, WrathTable>(b),
            Self::WorldStateUI => load_table_to_enum::<world_state_ui::WorldStateUI, WrathTable>(b),
            Self::WorldStateZoneSounds => load_table_to_enum::<world_state_zone_sounds::WorldStateZoneSounds, WrathTable>(b),
            Self::WowError_Strings => load_table_to_enum::<wow_error_strings::WowError_Strings, WrathTable>(b),
            Self::ZoneIntroMusicTable => load_table_to_enum::<zone_intro_music_table::ZoneIntroMusicTable, WrathTable>(b),
            Self::ZoneMusic => load_table_to_enum::<zone_music::ZoneMusic, WrathTable>(b),
            Self::gtBarberShopCostBase => load_table_to_enum::<gt_barber_shop_cost_base::gtBarberShopCostBase, WrathTable>(b),
            Self::gtChanceToMeleeCrit => load_table_to_enum::<gt_chance_to_melee_crit::gtChanceToMeleeCrit, WrathTable>(b),
            Self::gtChanceToMeleeCritBase => load_table_to_enum::<gt_chance_to_melee_crit_base::gtChanceToMeleeCritBase, WrathTable>(b),
            Self::gtChanceToSpellCrit => load_table_to_enum::<gt_chance_to_spell_crit::gtChanceToSpellCrit, WrathTable>(b),
            Self::gtChanceToSpellCritBase => load_table_to_enum::<gt_chance_to_spell_crit_base::gtChanceToSpellCritBase, WrathTable>(b),
            Self::gtCombatRatings => load_table_to_enum::<gt_combat_ratings::gtCombatRatings, WrathTable>(b),
            Self::gtNPCManaCostScaler => load_table_to_enum::<gt_npc_mana_cost_scaler::gtNPCManaCostScaler, WrathTable>(b),
            Self::gtOCTClassCombatRatingScalar => load_table_to_enum::<gt_oct_class_combat_rating_scalar::gtOCTClassCombatRatingScalar, WrathTable>(b),
            Self::gtOCTRegenHP => load_table_to_enum::<gt_oct_regen_hp::gtOCTRegenHP, WrathTable>(b),
            Self::gtOCTRegenMP => load_table_to_enum::<gt_oct_regen_mp::gtOCTRegenMP, WrathTable>(b),
            Self::gtRegenHPPerSpt => load_table_to_enum::<gt_regen_hp_per_spt::gtRegenHPPerSpt, WrathTable>(b),
            Self::gtRegenMPPerSpt => load_table_to_enum::<gt_regen_mp_per_spt::gtRegenMPPerSpt, WrathTable>(b),
        }
    }

}
impl DbcTableWriter for WrathTable {
    fn write(self, w: &mut impl std::io::Write) -> Result<(), std::io::Error> {
        match self {
            Self::Achievement(t) => t.write(w),
            Self::Achievement_Category(t) => t.write(w),
            Self::Achievement_Criteria(t) => t.write(w),
            Self::AnimationData(t) => t.write(w),
            Self::AreaGroup(t) => t.write(w),
            Self::AreaPOI(t) => t.write(w),
            Self::AreaTable(t) => t.write(w),
            Self::AreaTrigger(t) => t.write(w),
            Self::AttackAnimKits(t) => t.write(w),
            Self::AttackAnimTypes(t) => t.write(w),
            Self::AuctionHouse(t) => t.write(w),
            Self::BankBagSlotPrices(t) => t.write(w),
            Self::BannedAddOns(t) => t.write(w),
            Self::BarberShopStyle(t) => t.write(w),
            Self::BattlemasterList(t) => t.write(w),
            Self::CameraShakes(t) => t.write(w),
            Self::Cfg_Categories(t) => t.write(w),
            Self::Cfg_Configs(t) => t.write(w),
            Self::CharBaseInfo(t) => t.write(w),
            Self::CharHairGeosets(t) => t.write(w),
            Self::CharHairTextures(t) => t.write(w),
            Self::CharSections(t) => t.write(w),
            Self::CharStartOutfit(t) => t.write(w),
            Self::CharTitles(t) => t.write(w),
            Self::CharVariations(t) => t.write(w),
            Self::CharacterFacialHairStyles(t) => t.write(w),
            Self::ChatChannels(t) => t.write(w),
            Self::ChatProfanity(t) => t.write(w),
            Self::ChrClasses(t) => t.write(w),
            Self::ChrRaces(t) => t.write(w),
            Self::CinematicCamera(t) => t.write(w),
            Self::CinematicSequences(t) => t.write(w),
            Self::CreatureDisplayInfo(t) => t.write(w),
            Self::CreatureDisplayInfoExtra(t) => t.write(w),
            Self::CreatureFamily(t) => t.write(w),
            Self::CreatureModelData(t) => t.write(w),
            Self::CreatureMovementInfo(t) => t.write(w),
            Self::CreatureSoundData(t) => t.write(w),
            Self::CreatureSpellData(t) => t.write(w),
            Self::CreatureType(t) => t.write(w),
            Self::CurrencyCategory(t) => t.write(w),
            Self::CurrencyTypes(t) => t.write(w),
            Self::DanceMoves(t) => t.write(w),
            Self::DeathThudLookups(t) => t.write(w),
            Self::DeclinedWord(t) => t.write(w),
            Self::DeclinedWordCases(t) => t.write(w),
            Self::DestructibleModelData(t) => t.write(w),
            Self::DungeonEncounter(t) => t.write(w),
            Self::DungeonMap(t) => t.write(w),
            Self::DungeonMapChunk(t) => t.write(w),
            Self::DurabilityCosts(t) => t.write(w),
            Self::DurabilityQuality(t) => t.write(w),
            Self::Emotes(t) => t.write(w),
            Self::EmotesText(t) => t.write(w),
            Self::EmotesTextData(t) => t.write(w),
            Self::EmotesTextSound(t) => t.write(w),
            Self::EnvironmentalDamage(t) => t.write(w),
            Self::Exhaustion(t) => t.write(w),
            Self::Faction(t) => t.write(w),
            Self::FactionGroup(t) => t.write(w),
            Self::FactionTemplate(t) => t.write(w),
            Self::FileData(t) => t.write(w),
            Self::FootprintTextures(t) => t.write(w),
            Self::FootstepTerrainLookup(t) => t.write(w),
            Self::GMSurveyAnswers(t) => t.write(w),
            Self::GMSurveyCurrentSurvey(t) => t.write(w),
            Self::GMSurveyQuestions(t) => t.write(w),
            Self::GMSurveySurveys(t) => t.write(w),
            Self::GMTicketCategory(t) => t.write(w),
            Self::GameObjectArtKit(t) => t.write(w),
            Self::GameObjectDisplayInfo(t) => t.write(w),
            Self::GameTables(t) => t.write(w),
            Self::GameTips(t) => t.write(w),
            Self::GemProperties(t) => t.write(w),
            Self::GlyphProperties(t) => t.write(w),
            Self::GlyphSlot(t) => t.write(w),
            Self::GroundEffectDoodad(t) => t.write(w),
            Self::GroundEffectTexture(t) => t.write(w),
            Self::HelmetGeosetVisData(t) => t.write(w),
            Self::HolidayDescriptions(t) => t.write(w),
            Self::HolidayNames(t) => t.write(w),
            Self::Holidays(t) => t.write(w),
            Self::Item(t) => t.write(w),
            Self::ItemBagFamily(t) => t.write(w),
            Self::ItemClass(t) => t.write(w),
            Self::ItemCondExtCosts(t) => t.write(w),
            Self::ItemDisplayInfo(t) => t.write(w),
            Self::ItemExtendedCost(t) => t.write(w),
            Self::ItemGroupSounds(t) => t.write(w),
            Self::ItemLimitCategory(t) => t.write(w),
            Self::ItemPetFood(t) => t.write(w),
            Self::ItemPurchaseGroup(t) => t.write(w),
            Self::ItemRandomProperties(t) => t.write(w),
            Self::ItemRandomSuffix(t) => t.write(w),
            Self::ItemSet(t) => t.write(w),
            Self::ItemSubClass(t) => t.write(w),
            Self::ItemSubClassMask(t) => t.write(w),
            Self::ItemVisualEffects(t) => t.write(w),
            Self::ItemVisuals(t) => t.write(w),
            Self::LFGDungeonExpansion(t) => t.write(w),
            Self::LFGDungeonGroup(t) => t.write(w),
            Self::LFGDungeons(t) => t.write(w),
            Self::LanguageWords(t) => t.write(w),
            Self::Languages(t) => t.write(w),
            Self::Light(t) => t.write(w),
            Self::LightFloatBand(t) => t.write(w),
            Self::LightIntBand(t) => t.write(w),
            Self::LightParams(t) => t.write(w),
            Self::LightSkybox(t) => t.write(w),
            Self::LiquidMaterial(t) => t.write(w),
            Self::LiquidType(t) => t.write(w),
            Self::LoadingScreenTaxiSplines(t) => t.write(w),
            Self::LoadingScreens(t) => t.write(w),
            Self::Lock(t) => t.write(w),
            Self::LockType(t) => t.write(w),
            Self::MailTemplate(t) => t.write(w),
            Self::Map(t) => t.write(w),
            Self::MapDifficulty(t) => t.write(w),
            Self::Material(t) => t.write(w),
            Self::Movie(t) => t.write(w),
            Self::MovieFileData(t) => t.write(w),
            Self::MovieVariation(t) => t.write(w),
            Self::NPCSounds(t) => t.write(w),
            Self::NameGen(t) => t.write(w),
            Self::NamesProfanity(t) => t.write(w),
            Self::NamesReserved(t) => t.write(w),
            Self::ObjectEffect(t) => t.write(w),
            Self::ObjectEffectGroup(t) => t.write(w),
            Self::ObjectEffectModifier(t) => t.write(w),
            Self::ObjectEffectPackage(t) => t.write(w),
            Self::ObjectEffectPackageElem(t) => t.write(w),
            Self::OverrideSpellData(t) => t.write(w),
            Self::Package(t) => t.write(w),
            Self::PageTextMaterial(t) => t.write(w),
            Self::PaperDollItemFrame(t) => t.write(w),
            Self::ParticleColor(t) => t.write(w),
            Self::PetPersonality(t) => t.write(w),
            Self::PetitionType(t) => t.write(w),
            Self::PowerDisplay(t) => t.write(w),
            Self::PvpDifficulty(t) => t.write(w),
            Self::QuestFactionReward(t) => t.write(w),
            Self::QuestInfo(t) => t.write(w),
            Self::QuestSort(t) => t.write(w),
            Self::QuestXP(t) => t.write(w),
            Self::RandPropPoints(t) => t.write(w),
            Self::Resistances(t) => t.write(w),
            Self::ScalingStatDistribution(t) => t.write(w),
            Self::ScalingStatValues(t) => t.write(w),
            Self::ScreenEffect(t) => t.write(w),
            Self::ServerMessages(t) => t.write(w),
            Self::SheatheSoundLookups(t) => t.write(w),
            Self::SkillCostsData(t) => t.write(w),
            Self::SkillLine(t) => t.write(w),
            Self::SkillLineAbility(t) => t.write(w),
            Self::SkillLineCategory(t) => t.write(w),
            Self::SkillRaceClassInfo(t) => t.write(w),
            Self::SkillTiers(t) => t.write(w),
            Self::SoundAmbience(t) => t.write(w),
            Self::SoundEmitters(t) => t.write(w),
            Self::SoundEntries(t) => t.write(w),
            Self::SoundEntriesAdvanced(t) => t.write(w),
            Self::SoundFilter(t) => t.write(w),
            Self::SoundFilterElem(t) => t.write(w),
            Self::SoundProviderPreferences(t) => t.write(w),
            Self::SoundSamplePreferences(t) => t.write(w),
            Self::SoundWaterType(t) => t.write(w),
            Self::SpamMessages(t) => t.write(w),
            Self::Spell(t) => t.write(w),
            Self::SpellCastTimes(t) => t.write(w),
            Self::SpellCategory(t) => t.write(w),
            Self::SpellChainEffects(t) => t.write(w),
            Self::SpellDescriptionVariables(t) => t.write(w),
            Self::SpellDifficulty(t) => t.write(w),
            Self::SpellDispelType(t) => t.write(w),
            Self::SpellDuration(t) => t.write(w),
            Self::SpellEffectCameraShakes(t) => t.write(w),
            Self::SpellFocusObject(t) => t.write(w),
            Self::SpellIcon(t) => t.write(w),
            Self::SpellItemEnchantment(t) => t.write(w),
            Self::SpellItemEnchantmentCondition(t) => t.write(w),
            Self::SpellMechanic(t) => t.write(w),
            Self::SpellMissile(t) => t.write(w),
            Self::SpellMissileMotion(t) => t.write(w),
            Self::SpellRadius(t) => t.write(w),
            Self::SpellRange(t) => t.write(w),
            Self::SpellRuneCost(t) => t.write(w),
            Self::SpellShapeshiftForm(t) => t.write(w),
            Self::SpellVisual(t) => t.write(w),
            Self::SpellVisualEffectName(t) => t.write(w),
            Self::SpellVisualKit(t) => t.write(w),
            Self::SpellVisualKitAreaModel(t) => t.write(w),
            Self::SpellVisualKitModelAttach(t) => t.write(w),
            Self::SpellVisualPrecastTransitions(t) => t.write(w),
            Self::StableSlotPrices(t) => t.write(w),
            Self::Startup_Strings(t) => t.write(w),
            Self::Stationery(t) => t.write(w),
            Self::StringLookups(t) => t.write(w),
            Self::SummonProperties(t) => t.write(w),
            Self::Talent(t) => t.write(w),
            Self::TalentTab(t) => t.write(w),
            Self::TaxiNodes(t) => t.write(w),
            Self::TaxiPath(t) => t.write(w),
            Self::TaxiPathNode(t) => t.write(w),
            Self::TeamContributionPoints(t) => t.write(w),
            Self::TerrainType(t) => t.write(w),
            Self::TerrainTypeSounds(t) => t.write(w),
            Self::TotemCategory(t) => t.write(w),
            Self::TransportAnimation(t) => t.write(w),
            Self::TransportPhysics(t) => t.write(w),
            Self::TransportRotation(t) => t.write(w),
            Self::UISoundLookups(t) => t.write(w),
            Self::UnitBlood(t) => t.write(w),
            Self::UnitBloodLevels(t) => t.write(w),
            Self::Vehicle(t) => t.write(w),
            Self::VehicleSeat(t) => t.write(w),
            Self::VehicleUIIndSeat(t) => t.write(w),
            Self::VehicleUIIndicator(t) => t.write(w),
            Self::VideoHardware(t) => t.write(w),
            Self::VocalUISounds(t) => t.write(w),
            Self::WMOAreaTable(t) => t.write(w),
            Self::WeaponImpactSounds(t) => t.write(w),
            Self::WeaponSwingSounds2(t) => t.write(w),
            Self::Weather(t) => t.write(w),
            Self::WorldChunkSounds(t) => t.write(w),
            Self::WorldMapArea(t) => t.write(w),
            Self::WorldMapContinent(t) => t.write(w),
            Self::WorldMapOverlay(t) => t.write(w),
            Self::WorldMapTransforms(t) => t.write(w),
            Self::WorldSafeLocs(t) => t.write(w),
            Self::WorldStateUI(t) => t.write(w),
            Self::WorldStateZoneSounds(t) => t.write(w),
            Self::WowError_Strings(t) => t.write(w),
            Self::ZoneIntroMusicTable(t) => t.write(w),
            Self::ZoneMusic(t) => t.write(w),
            Self::gtBarberShopCostBase(t) => t.write(w),
            Self::gtChanceToMeleeCrit(t) => t.write(w),
            Self::gtChanceToMeleeCritBase(t) => t.write(w),
            Self::gtChanceToSpellCrit(t) => t.write(w),
            Self::gtChanceToSpellCritBase(t) => t.write(w),
            Self::gtCombatRatings(t) => t.write(w),
            Self::gtNPCManaCostScaler(t) => t.write(w),
            Self::gtOCTClassCombatRatingScalar(t) => t.write(w),
            Self::gtOCTRegenHP(t) => t.write(w),
            Self::gtOCTRegenMP(t) => t.write(w),
            Self::gtRegenHPPerSpt(t) => t.write(w),
            Self::gtRegenMPPerSpt(t) => t.write(w),
        }
    }

}
impl std::str::FromStr for WrathTableName {
    type Err = crate::DbcError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Achievement" => Ok(WrathTableName::Achievement),
            "Achievement_Category" => Ok(WrathTableName::Achievement_Category),
            "Achievement_Criteria" => Ok(WrathTableName::Achievement_Criteria),
            "AnimationData" => Ok(WrathTableName::AnimationData),
            "AreaGroup" => Ok(WrathTableName::AreaGroup),
            "AreaPOI" => Ok(WrathTableName::AreaPOI),
            "AreaTable" => Ok(WrathTableName::AreaTable),
            "AreaTrigger" => Ok(WrathTableName::AreaTrigger),
            "AttackAnimKits" => Ok(WrathTableName::AttackAnimKits),
            "AttackAnimTypes" => Ok(WrathTableName::AttackAnimTypes),
            "AuctionHouse" => Ok(WrathTableName::AuctionHouse),
            "BankBagSlotPrices" => Ok(WrathTableName::BankBagSlotPrices),
            "BannedAddOns" => Ok(WrathTableName::BannedAddOns),
            "BarberShopStyle" => Ok(WrathTableName::BarberShopStyle),
            "BattlemasterList" => Ok(WrathTableName::BattlemasterList),
            "CameraShakes" => Ok(WrathTableName::CameraShakes),
            "Cfg_Categories" => Ok(WrathTableName::Cfg_Categories),
            "Cfg_Configs" => Ok(WrathTableName::Cfg_Configs),
            "CharBaseInfo" => Ok(WrathTableName::CharBaseInfo),
            "CharHairGeosets" => Ok(WrathTableName::CharHairGeosets),
            "CharHairTextures" => Ok(WrathTableName::CharHairTextures),
            "CharSections" => Ok(WrathTableName::CharSections),
            "CharStartOutfit" => Ok(WrathTableName::CharStartOutfit),
            "CharTitles" => Ok(WrathTableName::CharTitles),
            "CharVariations" => Ok(WrathTableName::CharVariations),
            "CharacterFacialHairStyles" => Ok(WrathTableName::CharacterFacialHairStyles),
            "ChatChannels" => Ok(WrathTableName::ChatChannels),
            "ChatProfanity" => Ok(WrathTableName::ChatProfanity),
            "ChrClasses" => Ok(WrathTableName::ChrClasses),
            "ChrRaces" => Ok(WrathTableName::ChrRaces),
            "CinematicCamera" => Ok(WrathTableName::CinematicCamera),
            "CinematicSequences" => Ok(WrathTableName::CinematicSequences),
            "CreatureDisplayInfo" => Ok(WrathTableName::CreatureDisplayInfo),
            "CreatureDisplayInfoExtra" => Ok(WrathTableName::CreatureDisplayInfoExtra),
            "CreatureFamily" => Ok(WrathTableName::CreatureFamily),
            "CreatureModelData" => Ok(WrathTableName::CreatureModelData),
            "CreatureMovementInfo" => Ok(WrathTableName::CreatureMovementInfo),
            "CreatureSoundData" => Ok(WrathTableName::CreatureSoundData),
            "CreatureSpellData" => Ok(WrathTableName::CreatureSpellData),
            "CreatureType" => Ok(WrathTableName::CreatureType),
            "CurrencyCategory" => Ok(WrathTableName::CurrencyCategory),
            "CurrencyTypes" => Ok(WrathTableName::CurrencyTypes),
            "DanceMoves" => Ok(WrathTableName::DanceMoves),
            "DeathThudLookups" => Ok(WrathTableName::DeathThudLookups),
            "DeclinedWord" => Ok(WrathTableName::DeclinedWord),
            "DeclinedWordCases" => Ok(WrathTableName::DeclinedWordCases),
            "DestructibleModelData" => Ok(WrathTableName::DestructibleModelData),
            "DungeonEncounter" => Ok(WrathTableName::DungeonEncounter),
            "DungeonMap" => Ok(WrathTableName::DungeonMap),
            "DungeonMapChunk" => Ok(WrathTableName::DungeonMapChunk),
            "DurabilityCosts" => Ok(WrathTableName::DurabilityCosts),
            "DurabilityQuality" => Ok(WrathTableName::DurabilityQuality),
            "Emotes" => Ok(WrathTableName::Emotes),
            "EmotesText" => Ok(WrathTableName::EmotesText),
            "EmotesTextData" => Ok(WrathTableName::EmotesTextData),
            "EmotesTextSound" => Ok(WrathTableName::EmotesTextSound),
            "EnvironmentalDamage" => Ok(WrathTableName::EnvironmentalDamage),
            "Exhaustion" => Ok(WrathTableName::Exhaustion),
            "Faction" => Ok(WrathTableName::Faction),
            "FactionGroup" => Ok(WrathTableName::FactionGroup),
            "FactionTemplate" => Ok(WrathTableName::FactionTemplate),
            "FileData" => Ok(WrathTableName::FileData),
            "FootprintTextures" => Ok(WrathTableName::FootprintTextures),
            "FootstepTerrainLookup" => Ok(WrathTableName::FootstepTerrainLookup),
            "GMSurveyAnswers" => Ok(WrathTableName::GMSurveyAnswers),
            "GMSurveyCurrentSurvey" => Ok(WrathTableName::GMSurveyCurrentSurvey),
            "GMSurveyQuestions" => Ok(WrathTableName::GMSurveyQuestions),
            "GMSurveySurveys" => Ok(WrathTableName::GMSurveySurveys),
            "GMTicketCategory" => Ok(WrathTableName::GMTicketCategory),
            "GameObjectArtKit" => Ok(WrathTableName::GameObjectArtKit),
            "GameObjectDisplayInfo" => Ok(WrathTableName::GameObjectDisplayInfo),
            "GameTables" => Ok(WrathTableName::GameTables),
            "GameTips" => Ok(WrathTableName::GameTips),
            "GemProperties" => Ok(WrathTableName::GemProperties),
            "GlyphProperties" => Ok(WrathTableName::GlyphProperties),
            "GlyphSlot" => Ok(WrathTableName::GlyphSlot),
            "GroundEffectDoodad" => Ok(WrathTableName::GroundEffectDoodad),
            "GroundEffectTexture" => Ok(WrathTableName::GroundEffectTexture),
            "HelmetGeosetVisData" => Ok(WrathTableName::HelmetGeosetVisData),
            "HolidayDescriptions" => Ok(WrathTableName::HolidayDescriptions),
            "HolidayNames" => Ok(WrathTableName::HolidayNames),
            "Holidays" => Ok(WrathTableName::Holidays),
            "Item" => Ok(WrathTableName::Item),
            "ItemBagFamily" => Ok(WrathTableName::ItemBagFamily),
            "ItemClass" => Ok(WrathTableName::ItemClass),
            "ItemCondExtCosts" => Ok(WrathTableName::ItemCondExtCosts),
            "ItemDisplayInfo" => Ok(WrathTableName::ItemDisplayInfo),
            "ItemExtendedCost" => Ok(WrathTableName::ItemExtendedCost),
            "ItemGroupSounds" => Ok(WrathTableName::ItemGroupSounds),
            "ItemLimitCategory" => Ok(WrathTableName::ItemLimitCategory),
            "ItemPetFood" => Ok(WrathTableName::ItemPetFood),
            "ItemPurchaseGroup" => Ok(WrathTableName::ItemPurchaseGroup),
            "ItemRandomProperties" => Ok(WrathTableName::ItemRandomProperties),
            "ItemRandomSuffix" => Ok(WrathTableName::ItemRandomSuffix),
            "ItemSet" => Ok(WrathTableName::ItemSet),
            "ItemSubClass" => Ok(WrathTableName::ItemSubClass),
            "ItemSubClassMask" => Ok(WrathTableName::ItemSubClassMask),
            "ItemVisualEffects" => Ok(WrathTableName::ItemVisualEffects),
            "ItemVisuals" => Ok(WrathTableName::ItemVisuals),
            "LFGDungeonExpansion" => Ok(WrathTableName::LFGDungeonExpansion),
            "LFGDungeonGroup" => Ok(WrathTableName::LFGDungeonGroup),
            "LFGDungeons" => Ok(WrathTableName::LFGDungeons),
            "LanguageWords" => Ok(WrathTableName::LanguageWords),
            "Languages" => Ok(WrathTableName::Languages),
            "Light" => Ok(WrathTableName::Light),
            "LightFloatBand" => Ok(WrathTableName::LightFloatBand),
            "LightIntBand" => Ok(WrathTableName::LightIntBand),
            "LightParams" => Ok(WrathTableName::LightParams),
            "LightSkybox" => Ok(WrathTableName::LightSkybox),
            "LiquidMaterial" => Ok(WrathTableName::LiquidMaterial),
            "LiquidType" => Ok(WrathTableName::LiquidType),
            "LoadingScreenTaxiSplines" => Ok(WrathTableName::LoadingScreenTaxiSplines),
            "LoadingScreens" => Ok(WrathTableName::LoadingScreens),
            "Lock" => Ok(WrathTableName::Lock),
            "LockType" => Ok(WrathTableName::LockType),
            "MailTemplate" => Ok(WrathTableName::MailTemplate),
            "Map" => Ok(WrathTableName::Map),
            "MapDifficulty" => Ok(WrathTableName::MapDifficulty),
            "Material" => Ok(WrathTableName::Material),
            "Movie" => Ok(WrathTableName::Movie),
            "MovieFileData" => Ok(WrathTableName::MovieFileData),
            "MovieVariation" => Ok(WrathTableName::MovieVariation),
            "NPCSounds" => Ok(WrathTableName::NPCSounds),
            "NameGen" => Ok(WrathTableName::NameGen),
            "NamesProfanity" => Ok(WrathTableName::NamesProfanity),
            "NamesReserved" => Ok(WrathTableName::NamesReserved),
            "ObjectEffect" => Ok(WrathTableName::ObjectEffect),
            "ObjectEffectGroup" => Ok(WrathTableName::ObjectEffectGroup),
            "ObjectEffectModifier" => Ok(WrathTableName::ObjectEffectModifier),
            "ObjectEffectPackage" => Ok(WrathTableName::ObjectEffectPackage),
            "ObjectEffectPackageElem" => Ok(WrathTableName::ObjectEffectPackageElem),
            "OverrideSpellData" => Ok(WrathTableName::OverrideSpellData),
            "Package" => Ok(WrathTableName::Package),
            "PageTextMaterial" => Ok(WrathTableName::PageTextMaterial),
            "PaperDollItemFrame" => Ok(WrathTableName::PaperDollItemFrame),
            "ParticleColor" => Ok(WrathTableName::ParticleColor),
            "PetPersonality" => Ok(WrathTableName::PetPersonality),
            "PetitionType" => Ok(WrathTableName::PetitionType),
            "PowerDisplay" => Ok(WrathTableName::PowerDisplay),
            "PvpDifficulty" => Ok(WrathTableName::PvpDifficulty),
            "QuestFactionReward" => Ok(WrathTableName::QuestFactionReward),
            "QuestInfo" => Ok(WrathTableName::QuestInfo),
            "QuestSort" => Ok(WrathTableName::QuestSort),
            "QuestXP" => Ok(WrathTableName::QuestXP),
            "RandPropPoints" => Ok(WrathTableName::RandPropPoints),
            "Resistances" => Ok(WrathTableName::Resistances),
            "ScalingStatDistribution" => Ok(WrathTableName::ScalingStatDistribution),
            "ScalingStatValues" => Ok(WrathTableName::ScalingStatValues),
            "ScreenEffect" => Ok(WrathTableName::ScreenEffect),
            "ServerMessages" => Ok(WrathTableName::ServerMessages),
            "SheatheSoundLookups" => Ok(WrathTableName::SheatheSoundLookups),
            "SkillCostsData" => Ok(WrathTableName::SkillCostsData),
            "SkillLine" => Ok(WrathTableName::SkillLine),
            "SkillLineAbility" => Ok(WrathTableName::SkillLineAbility),
            "SkillLineCategory" => Ok(WrathTableName::SkillLineCategory),
            "SkillRaceClassInfo" => Ok(WrathTableName::SkillRaceClassInfo),
            "SkillTiers" => Ok(WrathTableName::SkillTiers),
            "SoundAmbience" => Ok(WrathTableName::SoundAmbience),
            "SoundEmitters" => Ok(WrathTableName::SoundEmitters),
            "SoundEntries" => Ok(WrathTableName::SoundEntries),
            "SoundEntriesAdvanced" => Ok(WrathTableName::SoundEntriesAdvanced),
            "SoundFilter" => Ok(WrathTableName::SoundFilter),
            "SoundFilterElem" => Ok(WrathTableName::SoundFilterElem),
            "SoundProviderPreferences" => Ok(WrathTableName::SoundProviderPreferences),
            "SoundSamplePreferences" => Ok(WrathTableName::SoundSamplePreferences),
            "SoundWaterType" => Ok(WrathTableName::SoundWaterType),
            "SpamMessages" => Ok(WrathTableName::SpamMessages),
            "Spell" => Ok(WrathTableName::Spell),
            "SpellCastTimes" => Ok(WrathTableName::SpellCastTimes),
            "SpellCategory" => Ok(WrathTableName::SpellCategory),
            "SpellChainEffects" => Ok(WrathTableName::SpellChainEffects),
            "SpellDescriptionVariables" => Ok(WrathTableName::SpellDescriptionVariables),
            "SpellDifficulty" => Ok(WrathTableName::SpellDifficulty),
            "SpellDispelType" => Ok(WrathTableName::SpellDispelType),
            "SpellDuration" => Ok(WrathTableName::SpellDuration),
            "SpellEffectCameraShakes" => Ok(WrathTableName::SpellEffectCameraShakes),
            "SpellFocusObject" => Ok(WrathTableName::SpellFocusObject),
            "SpellIcon" => Ok(WrathTableName::SpellIcon),
            "SpellItemEnchantment" => Ok(WrathTableName::SpellItemEnchantment),
            "SpellItemEnchantmentCondition" => Ok(WrathTableName::SpellItemEnchantmentCondition),
            "SpellMechanic" => Ok(WrathTableName::SpellMechanic),
            "SpellMissile" => Ok(WrathTableName::SpellMissile),
            "SpellMissileMotion" => Ok(WrathTableName::SpellMissileMotion),
            "SpellRadius" => Ok(WrathTableName::SpellRadius),
            "SpellRange" => Ok(WrathTableName::SpellRange),
            "SpellRuneCost" => Ok(WrathTableName::SpellRuneCost),
            "SpellShapeshiftForm" => Ok(WrathTableName::SpellShapeshiftForm),
            "SpellVisual" => Ok(WrathTableName::SpellVisual),
            "SpellVisualEffectName" => Ok(WrathTableName::SpellVisualEffectName),
            "SpellVisualKit" => Ok(WrathTableName::SpellVisualKit),
            "SpellVisualKitAreaModel" => Ok(WrathTableName::SpellVisualKitAreaModel),
            "SpellVisualKitModelAttach" => Ok(WrathTableName::SpellVisualKitModelAttach),
            "SpellVisualPrecastTransitions" => Ok(WrathTableName::SpellVisualPrecastTransitions),
            "StableSlotPrices" => Ok(WrathTableName::StableSlotPrices),
            "Startup_Strings" => Ok(WrathTableName::Startup_Strings),
            "Stationery" => Ok(WrathTableName::Stationery),
            "StringLookups" => Ok(WrathTableName::StringLookups),
            "SummonProperties" => Ok(WrathTableName::SummonProperties),
            "Talent" => Ok(WrathTableName::Talent),
            "TalentTab" => Ok(WrathTableName::TalentTab),
            "TaxiNodes" => Ok(WrathTableName::TaxiNodes),
            "TaxiPath" => Ok(WrathTableName::TaxiPath),
            "TaxiPathNode" => Ok(WrathTableName::TaxiPathNode),
            "TeamContributionPoints" => Ok(WrathTableName::TeamContributionPoints),
            "TerrainType" => Ok(WrathTableName::TerrainType),
            "TerrainTypeSounds" => Ok(WrathTableName::TerrainTypeSounds),
            "TotemCategory" => Ok(WrathTableName::TotemCategory),
            "TransportAnimation" => Ok(WrathTableName::TransportAnimation),
            "TransportPhysics" => Ok(WrathTableName::TransportPhysics),
            "TransportRotation" => Ok(WrathTableName::TransportRotation),
            "UISoundLookups" => Ok(WrathTableName::UISoundLookups),
            "UnitBlood" => Ok(WrathTableName::UnitBlood),
            "UnitBloodLevels" => Ok(WrathTableName::UnitBloodLevels),
            "Vehicle" => Ok(WrathTableName::Vehicle),
            "VehicleSeat" => Ok(WrathTableName::VehicleSeat),
            "VehicleUIIndSeat" => Ok(WrathTableName::VehicleUIIndSeat),
            "VehicleUIIndicator" => Ok(WrathTableName::VehicleUIIndicator),
            "VideoHardware" => Ok(WrathTableName::VideoHardware),
            "VocalUISounds" => Ok(WrathTableName::VocalUISounds),
            "WMOAreaTable" => Ok(WrathTableName::WMOAreaTable),
            "WeaponImpactSounds" => Ok(WrathTableName::WeaponImpactSounds),
            "WeaponSwingSounds2" => Ok(WrathTableName::WeaponSwingSounds2),
            "Weather" => Ok(WrathTableName::Weather),
            "WorldChunkSounds" => Ok(WrathTableName::WorldChunkSounds),
            "WorldMapArea" => Ok(WrathTableName::WorldMapArea),
            "WorldMapContinent" => Ok(WrathTableName::WorldMapContinent),
            "WorldMapOverlay" => Ok(WrathTableName::WorldMapOverlay),
            "WorldMapTransforms" => Ok(WrathTableName::WorldMapTransforms),
            "WorldSafeLocs" => Ok(WrathTableName::WorldSafeLocs),
            "WorldStateUI" => Ok(WrathTableName::WorldStateUI),
            "WorldStateZoneSounds" => Ok(WrathTableName::WorldStateZoneSounds),
            "WowError_Strings" => Ok(WrathTableName::WowError_Strings),
            "ZoneIntroMusicTable" => Ok(WrathTableName::ZoneIntroMusicTable),
            "ZoneMusic" => Ok(WrathTableName::ZoneMusic),
            "gtBarberShopCostBase" => Ok(WrathTableName::gtBarberShopCostBase),
            "gtChanceToMeleeCrit" => Ok(WrathTableName::gtChanceToMeleeCrit),
            "gtChanceToMeleeCritBase" => Ok(WrathTableName::gtChanceToMeleeCritBase),
            "gtChanceToSpellCrit" => Ok(WrathTableName::gtChanceToSpellCrit),
            "gtChanceToSpellCritBase" => Ok(WrathTableName::gtChanceToSpellCritBase),
            "gtCombatRatings" => Ok(WrathTableName::gtCombatRatings),
            "gtNPCManaCostScaler" => Ok(WrathTableName::gtNPCManaCostScaler),
            "gtOCTClassCombatRatingScalar" => Ok(WrathTableName::gtOCTClassCombatRatingScalar),
            "gtOCTRegenHP" => Ok(WrathTableName::gtOCTRegenHP),
            "gtOCTRegenMP" => Ok(WrathTableName::gtOCTRegenMP),
            "gtRegenHPPerSpt" => Ok(WrathTableName::gtRegenHPPerSpt),
            "gtRegenMPPerSpt" => Ok(WrathTableName::gtRegenMPPerSpt),
            _ => Err(crate::DbcError::InvalidTableName(s.to_string()))
        }
    }
}

